- completions/python
Add completion for python zip archives
> Completion for python zip archives

- completions/Makefile.am
- completions/tipc
- test/completion/tipc.exp
- test/lib/completions/tipc.exp
tipc is a user space configuration tool for the TIPC protocol which is
part of the mainline Linux Kernel. The tipc tool itself is part of the
iproute2 package which is present in most common Linux distributions.
> tipc: add tipc completions

- completions/tipc
> tipc: fix some minor errors

- completions/Makefile.am
- completions/ebtables
- test/completion/ebtables.exp
- test/docker/Dockerfile-ubuntu14
- test/lib/completions/ebtables.exp
Based on the iptables completion, but slightly adapted as commands differ a little
> ebtables: new completion

- bash_completion
Ref https://docs.oracle.com/middleware/1221/wls/WLCOH/create-application.htm#WLCOH722
> Added "*.gar" to unzip/zipinfo.

- completions/Makefile.am
- completions/tox
- test/completion/tox.exp
- test/lib/completions/tox.exp
documentation for it at https://tox.readthedocs.io/en/latest/
> add completion rules for the tox tool

- completions/kldunload
While here, save the resulting suggestions as an array to COMPREPLY.
This is a follow up to #184.
BTW, I've started to tinker with the testing suite. I need a little bit more time for this.
Also, thanks for maintaining this repository :+1:
> kldunload: Increase robustness of compgen filters

- bash_completion
> _filedir: Refactor to remove heredoc-dependent loop

- completions/tar
(description in the commit message)
> tar: Support completions for zstd compression extensions

- bash_completion
Please find a new file extension we can use with unzip.
Thx for your job
> Associate  *.xar (eXist-db application package) to unzip

- completions/Makefile.am
- completions/_xm
I ran the test case locally and I didn't see any regressions.
> xm: Remove completion for unavailable command

- completions/unrar
Add exe extension to support some common rar self-extracting (SFX) archives
> Add exe extension to support some common rar self-extracting (SFX) archives

- bash_completion
Extensions sourced from mplayer.
> Use kaffeine completions for totem

- completions/ip
- test/t/test_ip.py
Implemented frequently used completions for via, dev, and existing
routes.
> Improve completion of ip route subcommands

- bash_completion
Android AAR is a ZIP container with required files:
https://developer.android.com/studio/projects/android-library.html#aar-contents
> support Android AAR libraries as 'unzip' file type

- bash_completion
- completions/ip
- completions/wol
change all
```
ip link show
```
to something like this
```
(ip -c=never link show || ip link show)
```
> fix issue #436 Color-Bug if ip is an alias

- completions/Makefile.am
- completions/ps
- test/t/Makefile.am
- test/t/test_ps.py
- test/test-cmd-list.txt
> Add ps completion

- bash_completion
I noticed this ommission while using totem but expect it to work also for the other commands sharing the completion.
> kaffeeine, dragon, totem: Add opus file extension

- bash_completion
Closes https://github.com/scop/bash-completion/issues/515
> fix(_known_hosts_real): protect against non-default $IFS

- bash_completion
https://wiki.freecadweb.org/File_Format_FCStd
> unzip, zipinfo: recognize FreeCAD files

- test/t/test_man.py
- test/t/test_tar.py
- test/t/unit/test_unit_known_hosts_real.py
- test/t/unit/test_unit_pgids.py
- test/t/unit/test_unit_pids.py
- test/t/unit/test_unit_pnames.py
Now that the test problems have been solved, I'd like to finish the fixes that had been pending.
> test(tar,known_hosts,p{gids,pids,names}): use "bash_env_saved"

- completions/Makefile.am
- completions/tree
- test/t/Makefile.am
- test/t/test_tree.py
- test/test-cmd-list.txt
Upstream doesn't seem that active, so I thought I'd just add it here, can maintain it.
> feat(tree): new completion

- .pre-commit-config.yaml
No resulting formatting changes.
> chore(deps): upgrade shfmt to 3.3.1

- completions/lrzip
- test/t/test_lrzip.py
Seems I've forgotten to open a MR for this.
> feat(lrzip): complete long option args

- test/setup.cfg
Hopefully fixes problems running pre-commit.
> test(mypy): set mypy_path, to find conftest

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .markdownlint.yaml
- .pre-commit-config.yaml
- .pymarkdown.json
See individual commits for details.
> Switch from markdownlint-cli to pymarkdown

- README.md
Unsure if the issue still exists, but it does not seem to have anything
to do with bash-completion or completions in the first place.
Closes https://github.com/scop/bash-completion/issues/607
> docs(readme): remove known problem related to cd and Makefiles

- .github/workflows/ci.yaml
Now that we have the image again.
> ci: test on fedoradev again

- bash_completion
- test/t/unit/test_unit_variables.py
> Fix `_variables` for failglob

- completions/ssh
- completions/tshark
- test/t/test_rsync.py
- test/t/test_ssh_copy_id.py
- test/t/test_sshfs.py
- test/t/test_tshark.py
- test/t/unit/test_unit_get_cword.py
Per https://github.com/scop/bash-completion/discussions/539#discussioncomment-864857
> refactor: completion internal variable renames

- completions/evince
- test/t/test_evince.py
https://gitlab.gnome.org/GNOME/evince/-/blob/32e832611b1e60834fc5797311d46b98a6e5f958/help/C/formats.page#L32
> feat(evince): complete on XPS and more comic book documents

- completions/firefox
Firefox is a very good SVG viewer and I use it for that purpose a lot. 
(Thanks for all the completions!)
> feat(firefox): Add svg file completion

- completions/fio
- test/t/test_fio.py
> feat(fio): update --crctest, --debug, and --terse-version arg completion

- bash_completion
Fixes https://github.com/scop/bash-completion/issues/515#issuecomment-1264741656
> fix(_known_hosts_real): work around custom IFS

- .github/renovate.json
- .pre-commit-config.yaml
- doc/testing.md
- helpers/python
- pyproject.toml
- test/requirements-dev.txt
- test/setup.cfg
_Much_ faster, and less config/maintenance chores.
> test(python): switch linting to Ruff

- completions/_udevadm
- completions/badblocks
- completions/cryptsetup
- completions/dnssec-keygen
- completions/dumpe2fs
- completions/e2freefrag
- completions/e2label
- completions/hddtemp
- completions/lilo
- completions/lvm
- completions/mdadm
- completions/mplayer
- completions/mutt
- completions/nsupdate
- completions/smartctl
- completions/tune2fs
Some of these might disappear soon due to other ongoing work, but just in case, doesn't hurt anyway.
> feat: default assignment consistency and fix

- completions/.gitignore
- completions/Makefile.am
- completions/_gaiacli
- completions/_gsctl
- test/fallback/completions/Makefile.am
- test/fallback/completions/gaiacli
- test/fallback/completions/gsctl
Mainly from https://github.com/spf13/cobra/blob/main/projects_using_cobra.md
> feat: more fallback 3rd party completion loaders

- bash_completion
- completions/cd
- test/t/unit/test_unit_compgen.py
https://github.com/scop/bash-completion/issues/948#issuecomment-1529412590
```bash
_comp_compgen [-al|-F sep] ARRAY COMPGEN_ARGS... -- CUR
_comp_compgen [-alR|-F sep|-c CUR|-v ARRAY] -- COMPGEN_ARGS...
```
> fix(_comp_compgen): change interface

- bash_completion
- completions/_modules
- completions/_yum
- completions/apt-cache
- completions/apt-get
- completions/asciidoc
- completions/bts
- completions/cvs
- completions/dict
- completions/iconv
- completions/list_lists
- completions/mutt
- completions/mysql
- completions/openssl
- completions/python
- completions/rpm
- completions/ssh
- completions/tar
- completions/vpnc
- completions/xrandr
This and that on the topic of API adjustments, see individual commits for details.
> refactor: more API related work

- completions/bzip2
- completions/carton
- completions/chronyc
- completions/dmypy
- completions/find
- completions/gcc
- completions/gdb
- completions/gssdp-discover
- completions/gzip
- completions/id
- completions/influx
- completions/info
- completions/lrzip
- completions/lz4
- completions/lzip
- completions/lzma
- completions/lzop
- completions/man
- completions/valgrind
- completions/xz
- completions/zopfli
These are the cases requiring manual editing but straightforward ones.
> fix: use `_comp_compgen` for simple cases

- completions/_hwclock
- completions/badblocks
- completions/dnssec-keygen
- completions/jps
- completions/links
- completions/ps
- completions/puppet
- completions/tar
- completions/zopfli
These are the remaining ones for the `_parse_{help,usage}` refactoring.
> refactor: remaining `_comp_compgen_{help,usage}` changes

- .github/workflows/ci.yaml
- README.md
- test/docker/entrypoint.sh
- test/t/Makefile.am
- test/t/conftest.py
See individual commits for details.
> build: distcheck fixes

- completions/.gitignore
- completions/Makefile.am
- completions/sha256sum
- test/t/Makefile.am
- test/t/test_b2sum.py
- test/test-cmd-list.txt
Add b2sum completion alongside other checksum command completions.
> feat(b2sum): new completion

- completions/.gitignore
- completions/Makefile.am
More `argcomplete` based ones here.
> feat: add more fallback 3rd party completion loaders

- completions/vpnc
Has probably been just missed.
> refactor(vpnc): rename function per naming guidelines

- completions/Makefile.am
- completions/_keyring
- test/fallback/completions/Makefile.am
- test/fallback/completions/keyring
https://github.com/jaraco/keyring#tab-completion
> feat(keyring): add fallback 3rd party completion loader

- bash_completion
- test/t/unit/test_unit_parse_help.py
> fix(_comp_compgen_help): allow dots to connect names in longopt

- completions/.gitignore
- completions/Makefile.am
- completions/_jungle
- completions/_kontena
- completions/_nvm
- completions/_pip
- test/fallback/completions/Makefile.am
- test/fallback/completions/jungle
- test/fallback/completions/kontena
- test/fallback/completions/nvm
- test/fallback/completions/pip
Ref. https://github.com/ohmybash/oh-my-bash/pull/477
> feat: add fallback 3rd-party completion loaders

- bash_completion
- test/t/unit/test_unit_initialize.py
> fix(_comp_initialize): fix completions of redirections without space

- completions/dot
- test/t/test_dot.py
> feat(dot): support filename extension .gv

- completions/ip
- test/t/test_ip.py
Currently it stops after completing the first option, although you should be able to choose multiple options.
I'll be happy for some pointers on how I can make it keep completing after the first option, but I think this is enough on its own.
> feat(ip): Add completion for monitor subcommand

- doc/Makefile.am
- doc/api-and-naming.md
Fixes #1124
I also added trivial grammatical fixes.
> fix(Makefile): include `api-and-naming.md` in dist

- completions/ip
- test/t/test_ip.py
Split this into a few commits, adding a function and using it in two places.
> Complete ip link types

- completions/ip
> fix(ip): Quote all instantiation of ip as "$1"

- completions/xmllint
- completions/xmlwf
Add suggestion for .rss files to xmllint; this suffix is pretty common for RSS feeds stored offline.
> feat(xmllint,xmlwf): also suggest *.rss files

- completions/Makefile.am
- completions/_rg
- test/fallback/completions/rg
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#complete
> feat(rg): add fallback 3rd party completion loader

- completions/ip
`ip netns delete` also supports the -all flag, I might add that in a follow up PR
> ip: Various ip net namespace fixes and feats

- completions/ip
This was missing from the help and man page, but worked for a while.
> fix(ip): Complete link change as well as set

- bash_completion
- completions/vncviewer
As mentioned in https://github.com/scop/bash-completion/pull/1212#discussion_r1642366683.
> refactor: normalize unset positions of call-once functions

- completions/curl
> feat(curl): Complete "%" for --trace

- completions/update-alternatives
- test/t/test_update_alternatives.py
> fix(update-alternatives): fix the "--help" parsing

- bash_completion
These are VS Code extension files,
https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix
> feat: associate unzip and friends with *.vsix

- completions/.gitignore
- completions/Makefile.am
- completions/fprintd-delete
- completions/fprintd-enroll
- test/t/Makefile.am
- test/t/test_fprintd_delete.py
- test/t/test_fprintd_enroll.py
- test/t/test_fprintd_list.py
- test/t/test_fprintd_verify.py
- test/test-cmd-list.txt
Submitting here, because there are multiple alternative (but compatible) implementations of projects including these tools in existence, at least https://fprint.freedesktop.org and https://github.com/uunicorn/open-fprintd.
> feat(fprintd-*): new completions

- test/t/test_gcc.py
Closes https://github.com/scop/bash-completion/issues/1201
> test(gcc): adjust -mtune=/-march= expectations for ppc

- test/fixtures/shared/bin/ip
Follow up to https://github.com/scop/bash-completion/pull/1090
> chore: Run shfmt on ip fixture

- completions/.gitignore
- completions/Makefile.am
https://aquaproj.github.io/docs/reference/usage/#aqua-completion
> feat(aqua): add 3rd party fallback completion loader

- completions/.gitignore
- completions/Makefile.am
https://github.com/sigstore/cosign/blob/main/doc/cosign_completion.md
> feat(cosign): add 3rd party fallback completion loader

- README.md
Parity change for what's on the [homebrew site](https://formulae.brew.sh/formula/bash-completion@2)
> Docs: Update OSX docs

- completions/.gitignore
- completions/Makefile.am
- completions/_coder
- completions/_jj
- test/fallback/completions/Makefile.am
- test/fallback/completions/coder
- test/fallback/completions/jj
Many additions, but most trivial, mainly aliasing.
> feat: add (many) more 3rd party fallback completion loaders

- completions/Makefile.am
- completions/_secret-tool
- test/fallback/completions/Makefile.am
- test/fallback/completions/secret-tool
Closes https://github.com/scop/bash-completion/issues/1317
> refactor(secret-tool): deprecate ours in favor of upstream

- completions/.gitignore
- completions/Makefile.am
https://gitlab.com/gitlab-org/cli/-/tree/main/docs/source/completion
> feat(glab): add 3rd party fallback completion loader

- completions/Makefile.am
- completions/_bombadil
- test/fallback/completions/Makefile.am
- test/fallback/completions/bombadil
https://github.com/oknozor/toml-bombadil#shell-completions
> feat(bombadil): add 3rd party fallback completion loader

- completions/.gitignore
- completions/Makefile.am
> feat(asdf): add 3rd-party fallback completion loader for "asdf"

- .github/workflows/scorecard.yaml
- README.md
> chore(ci): add OpenSSF Scorecard
