- bash_completion
- test/fixtures/scp/config
- test/fixtures/sftp/config
- test/lib/completions/scp.exp
- test/lib/completions/sftp.exp
When connecting to a host listed after Hostname the options in the
config file are not applied, so don't complete these names accordingly.
If you still want some hosts completed, just add an other entry with
just Host <yourhostname> at the end of the config file.
This closes scop/bash-completion#3 and https://bugs.debian.org/689585
> Don't complete hostnames found after Hostname in ~/.ssh/config

- completions/xmllint
- completions/xmlwf
- completions/xsltproc
I use xmllint and xsltproc on Mallard page files almost daily. It's unpleasant with bash refusing to complete on those files. This patch makes it pleasant again.
> xmllint, xmlwf, xsltproc: Complete on Mallard *.page files

- completions/lvm
The current lvm completion has problems when executing the commands related with physical volumes.
These 3 patches correct completion of all lvm commands related with physical volumes.
> Fixe lvm completion related with physical volumes

- bash_completion
- test/unit/_variables.exp
* Complete `${arr[` with `${arr[idx1]} ${arr[idx2]}`, etc ..
* Complete `${arr[idx]` with closing curly brace
* Complete `${ar` with `${arr[` (nospace) if it is the only matching variable
* Complete `${arr[@` with `${arr[@]}` (also for `*`)
* Support completion of `${!var` and `${#var` forms for both regular and array variables
> Support completing array variables and expansions

- completions/function
- test/lib/completions/declare.exp
* complete variable names when appropriate
* complete more than one var/fun name
* complete `+` options in addition to `-` options
* recognize `-F` in addition to `-f`
> Better handling of typeset/declare

- completions/bk
The line didn't correctly parse the 'bk help topics'
manpage.
This is a cheap bugfix that makes this completion function at least do what it was intending.
Later we will suggest a better function, but for now this is much better than the current code.
BTW the output of `bk help topics` is as follows:
```
All(sum)                    BitKeeper User's Manual                   All(sum)
NAME
All - summary of all commands and topics
COMMANDS
bk abort - abort a failed pull or push
bk admin - administer BitKeeper files
bk alias - manage aliases for lists of components
bk annotate - provide annotated listings of one or more source files
bk attach - attach a component repository to a product repository
...
```
> The BitKeeper completion used the wrong set of commands

- completions/tar
Causes an unknown argument error to be output. Tested with busybox tar.
> tar: silence --version's stderr output

- completions/perl
- helpers/perl
Extend the perl helper to optionally include *.pod files, then include those only for perldoc completions.
For example, this allows the completion of `perl -MMoose::M` to continue to show only actual perl modules than can be loaded, while allowing the completion of `perldoc Moose::M` to include the Moose::Manual* documentation.
> Support pod document files for perldoc

- bash_completion
Enable unzip to handle iOS ipa files (https://en.wikipedia.org/wiki/.ipa)
> .ipa is just a zip file and we should let unzip handle it

- completions/Makefile.am
- completions/mr
- test/completion/mr.exp
- test/lib/completions/mr.exp
This PR adds completion for [myrepos](https://myrepos.branchable.com/), a tool used to manage multiple local repositories at once.
I'd appreciate some input on the test suite in particular. I'm not sure how to test the following completions:
* `mr run <TAB>` should complete commands
* `mr bootstrap <TAB>` suggests standard input (`-`) to the user along with the normal list of files. Once the user starts typing a filename, `-` should not longer be suggested.
Thanks in advance for your feedback.
> Add completion for myrepos (mr)

- completions/ssh-keygen
OpenSSH supports ed25519 since version 6.5 (Jan 2014, http://www.openssh.com/txt/release-6.5), this patch adds a completion for this key type.
> ssh-keygen: support ed25519 keys

- bash_completion
- test/fixtures/_known_hosts_real/.ssh/config_relative_path
- test/fixtures/_known_hosts_real/config_full_path
- test/fixtures/_known_hosts_real/config_include
- test/fixtures/_known_hosts_real/config_include_recursion
- test/unit/_known_hosts_real.exp
This patch adds support for the Include directive in _ssh_config_ files (issue #70).
It adds the included (readable) files to the `config` variable to be later processed by the `_known_hosts_real()` function.
> Add support for Include in ssh config (#70)

- completions/ant
- test/fixtures/ant/build-with-import.xml
- test/fixtures/ant/imported-build.xml
- test/lib/completions/ant.exp
This PR adds support for `<import>` tags.
It is only basic support as it does not care about `basedir` setting.
> ant: parse targets in imported buildfiles

- completions/python
Add support for Python gui source files
Especially in Windows land, the extension ".pyw" is used to indicate a
python file is intended to be launched without a console window. You can
still just run these from python.
> Support for python gui source files

- completions/Makefile.am
- completions/ssh
[sidedoor][sidedoor] maintains an SSH connection
and is packaged in Debian. Although its primary use is as a
daemon, it can be invoked like autossh.
[sidedoor]: https://github.com/daradib/sidedoor
> Add sidedoor to _ssh() completion

- completions/make
On OSX, using BSD sed, this error occurs when trying to complete a space, this error occurs:
'make sed: 46: /dev/fd/63: extra characters at the end of d command'
This does not occur with the above change or with gsed.
> Fix bug in 'make' completion when using BSD sed

- completions/ccache
- test/lib/completions/ccache.exp
This fixes the ccache completion function so that completing the
compiler’s flags works correctly.
I took the fixes from the sudo completion code, which works fine.
> ccache: fix completing compiler's flags

- Makefile.am
This was broken in c41a76237bc9dcbfa326eeddd026b66d7646d91d.
Fixes #131.
> Makefile: update default compatdir

- test/lib/library.exp
- test/run
Add an option, complementary to --timeout, that can be used to alter
the match buffer size for expect (match_max).
> test: Support overriding default match buffer size

- completions/lftp
Support the new ~/.local/share/lftp/bookmarks bookmark location. Both locations
are possible, depending on whether ~/.lftp exists.
Bug: https://bugs.gentoo.org/527450
Original-Author: Andrew Petelin <adrianopol@gmail.com>
> lftp: Support ~/.local/... bookmark location

- completions/tar
The --lzop option can be used for tar to read lzop-compressed archives, often with the .lzo extension. We extend the regular expression to support completion of .lzo tar files as well.
> Add support for .lzo extension (--lzop) to tar

- completions/man
`manpath` or `man -w` print out the path based on `$MANPATH`, so it's not needed to be examined directly, otherwise it must be somehow expanded to make sure default man path is included.
> * man - don't use $MANPATH directly (#160)

- doc/testing.txt
- test/config/bashrc
- test/lib/library.exp
When running bash with `--rcfile` it skips loading the user bashrc, but
it doesn't skip loading the system bashrc.
If bash completions is installed and loaded from system bashrc, this
causes an error:
```
FAIL: ERROR Unexpected output from bash command "BASH_COMPLETION_COMPAT_DIR=$(cd "$SRCDIR/.."; pwd)/completions"
FAIL: ERROR executing bash command "BASH_COMPLETION_COMPAT_DIR=$(cd "$SRCDIR/.."; pwd)/completions"
```
In order to avoid that, run bash with the `--norc` option which skips
loading any bashrc, and immediately source our `config/bashrc`.
It is important to set INPUTRC and PS1 before running bash.
> test: run bash with --norc to avoid system bashrc

- completions/openssl
This patch set adds completion for openssl commands: genpkey, pkey, pkeyparam, and pkeyutl.
They have been requested by a Debian user [1], and, although upstream support was not available, I thought it could be a good learning exercise, since I have never programmed bash-completion.
I split the changes into 5 different patches, one for each openssl command, and a fifth that suggests arguments to the -kdf option.  I'm OK with squashing the changes...  I just split them because I thought it could ease review, specially for the fifth patch (and also because CONTRIBUTING.md suggests small changes...  Maybe it got too small?).
[1] https://bugs.debian.org/779814#10
> Completions for openssl *pkey* commands

- bash_completion
By default, associative arrays are local. If bash_completion is sourced from
within a funciton, they won't propagate to the caller, and the system is not
initialized properly. By making this explicitly global, it propagates as
expected.
> Declare _xspecs as global.

- completions/tshark
A couple of updates and fixes:
* tshark: update -T and -t completions
The new -t values are available since 1.12 while the the most recent -T
value was added in 2.4. Current as of v2.9.0rc0-2173-g9fcb4af6b6.
Hardcode options as executing tshark can be slow while the options do
not change that option.
* tshark: prevent a single-character file from breaking -G completion
* tshark: support .gz and .cap files for -r expansion
Wireshark performs content sniffing to recognize the file type, so
perhaps the extension filter should be removed completely. Until that
happens, let's recognize .gz-compressed captures and .cap files too.
As for further improvements, executing an non-optimized debug build of `tshark` is slow (for `-O`, `-G`, etc.). Are there any standard methods for memoization that can …
> Tshark completion updates and fixes

- completions/.gitignore
- completions/Makefile.am
- completions/chromium-browser
Only Ubuntu calls it "chromium-browser", all others (Debian, Arch Linux,
Fedora) call it "chromium". When built from source, the resulting binary
is called "chrome".
___
This will likely not suggest anything because `chromium --help` by default does not contain any options. It is recommended to apply #242 for more helpful completion.
For reference, this is my `chromium --help` output:
```
Chromium launcher v6 -- for Chromium help, see chromium(1)
Custom flags are read from the following file:
/home/peter/.config/chromium-flags.conf
Arguments contained in that file are split on whitespace and shell quoting
rules apply but no further parsing is performed. Lines starting with a hash
symbol (#) are skipped. Lines with unbalanced quotes are skipped as well.
Currently detected flags: …
```
> chromium-browser: consider chrome and chromium as aliases

- README.md
- doc/testing.txt
- test/t/conftest.py
There should only be one marker, so get_closest_marker (introduced with
pytest 3.6.0 (2018-05-23)) is the most accurate replacement.
Fixes the following warning while running tests:
test/t/conftest.py:155: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
___
This reduces noice while running tests with newer pytest versions (locally and with Travis). A documentation update in doc/testing.rst is probably necessary though as only Debian buster and Ubuntu cosmic have the required pytest version. Older distributions have to install a more recent pytest version using pip.
> conftest: fix RemovedInPytest4Warning due to use of node.get_marker

- bash_completion
Similarly to gz-compressed and bzip2-compressed files Okular also supports xz-compressed files (as of https://github.com/KDE/okular/commit/14aec8a8dd0156d030290b9d872074f07b3c9d01). This commit adds support for such files with a `.xz` or `.XZ` extension.
> okular: Added support for xz-compressed files.

- completions/7z
The 7z command line tool supports unpacking `.msi` files. Reference: https://www.7-zip.org/
(I have also tried it personally and noted that bash-completion didn't include these files in its completion.)
> 7z: add .msi support

- completions/dpkg
This problem and fix have been reported by Paul Wise in Debian [1].  I have tested that it indeed fixes the problem by reproducing it without his fix, then observing that the problem was gone with the fix.  Steps to reproduced are provided in the original bug report [1].
[1] https://bugs.debian.org/907294
> List held packages in dpkg

- test/t/conftest.py
While working on a completion for `ethtool` (for which I will submit another PR shortly), I encountered some timeout errors in the test suite.  I found that the same race condition as 85275cf5 exists in `assert_complete` for multiple completions (case 0 of the expect matches).  If the magic mark is not included in `expect()`, it may or may not have been written by bash at the point `bash.sendintr()` is called.   If the interrupt is delivered before magic mark has finished printing, it can corrupt the prompt and cause `bash.expect_exact(PS1)` to timeout.
This pull request includes `MAGIC_MARK` in the case 0 regex, which fixes the issue.
It also increases the pty width to 160 columns to avoid corrupting the magic mark due to bash line wrapping, which happens for completed commands where the …
> Improve test reliability detecting magic mark

- bash_completion
The option --recursive for `grep` command did not show up
because it was overriden by --directories.
> Don't override any pattern by its repetition in _longopt

- test/t/test_rpm2tgz.py
Fix typo in path, as well as missing format string argument in rpm2tgz
test.  This resulted in the expected value missing the directory,
causing the test to fail.
> test_rpm2tgz: Fix expected output

- test/t/test_chromium_browser.py
Skip test_2 when help for chromium-browser is not available.  Follows
similar logic used in other tests.  Fixes test failure on Gentoo
where the manpage of chromium is missing for some reason.
> test_chromium_browser: Skip test_2 if 'chromium-browser --help' fails

- test/t/test_arp.py
Skip test_arp if 'arp' yields no output.  This e.g. happens when
the host is not networking-enabled.
> test_arp: Skip if ARP tables are empty

- completions/perltidy
Lintian enforces `perltidy` in its code base, including test scripts written in Perl. When `perltidy` is invoked, such arguments are not completed. This commit catches test scripts ending in `*.t`.
> For perltidy, catch *.t test scripts.

- completions/apt-get
The output from `apt-cache madison` consist of two lines only and does not require using regular expressions.
> apt-get: fix if the version number contains a colon

- bash_completion
.aab is the extension used for Android App Bundles, which are zip files.
https://developer.android.com/guide/app-bundle
> Add .aab to unzip extension list.

- Makefile.am
- bash-completion-config.cmake.in
- bash-completion.pc.in
- bash_completion.sh.in
- completions/Makefile.am
- configure.ac
- helpers/Makefile.am
Using `pkg-config` options the user has the possibility to redefine key values present in the `.pc` files.
Due to this `compatdir`, `completionsdir` and `helpersdir` that are defined in the generated pkg-config `.pc` file should be relative paths.
This helps any pkg-config user to set these variables to proper directories by using the `define-variable` command line argument.
> pkg-config: Relative paths

- completions/cppcheck
'--std=posix' is deprecated and will be removed.
See this Cppcheck commit:
https://github.com/danmar/cppcheck/commit/cb06aebdab894c2ca767869889df8e1175aeb379
> cppcheck: Remove deprecated option 'posix'  for '--std='

- completions/screen
an important feature of GNU screen is its usefulness as a serial terminal.  Autocomplete normally does not work with serial devices because they are not real files, so this change autocompletes serial ports after $ screen /dev<TAB>
> allow autocomplete with serial ports

- completions/gcc
- test/t/test_gcc.py
GCC 9.1 will come up with a new option that will provide option hints. It's more precise that parsing of gcc --help output. First patch does a clean-up where I unified option providing. And I removed legacy compiler binary names.
> Support new GCC --completion option for bash completion

- completions/cryptsetup
Adding a completion for $cryptsetup luksChangeKey
> Adding a completion for $cryptsetup luksChangeKey

- completions/jarsigner
Adding a completion for `jarsigner` with `*.apk` files. This bug emerged from the downstream Debian bash-completion. The bug identifier is: **Debian Bug report logs - #907635**
> Adding a completion for $jarsigner  *.apk files

- completions/.gitignore
- completions/Makefile.am
- completions/python
Debian, Ubuntu, and likely other distributions install the Python executable with a minor version (e.g. `python2.7`, `python3.8`) in addition to the major version (`python2`, `python3`) and unversioned (`python`) aliases.  Apply the completion to the minor versioned executables for versions supported in the last 3 years.
Thanks for considering,
Kevin
> python: support executables with minor version

- bash_completion
Avoids calling command_not_found_handle which might take considerable
time.
---
For instance on my system command_not_found_handle takes more than 200ms. I don't want this delay every time I complete hostname!
> Check that ruptime is present before calling

- completions/lintian
In Ubuntu, automatic debug packages use the non-standard .ddeb suffix:
https://wiki.ubuntu.com/Debug%20Symbol%20Packages
This commit implements path completion for them, and also for Debian's buildinfo files. It was tested locally.
> lintian: complete paths for Ubuntu automatic debug symbols and Debian's buildinfo files

- bash_completion
- completions/ip
The original PR looks like abandoned. I added some improvements and hopefully addressed the issues mentioned there.
- Embed the available netns part inside completion
- Add 2>/dev/null for ls command
- Add missing subcommands
- Only complete the netns name once after subcmd
> ip: add support for netns (based on #21)

- completions/ssh
Mostly based on the upstream code:
https://github.com/openssh/openssh-portable/blob/master/ssh.c#L738
One place for improvement would be accepting case insensitive aliases, but I was not sure how to do that easily on fast review of the manual pages.
> Add new ssh -Q completions in OpenSSH 8.2p1

- bash_completion
I was getting `~/.bash_completion is a directory` error messages, which I did not like seeing on every ssh login. So I added a `-f` to make sure it's a file, in addition to the other checks.
Perhaps this isn't quite correct; among other things, installing bash_completion and then having a directory called ~/.bash_completion might be a problem. But I thought I'd submit my fix anyway.
Thanks!
> fix for "bash_completion is a directory" error message

- completions/tshark
- test/t/test_tshark.py
The current autocomplete only accepts pcap/pcapng(.gz), but Tshark allows many other [file types](https://www.wireshark.org/docs/wsug_html_chunked/ChIOOpenSection.html#ChIOInputFormatsSection).
I think instead of adding all those types to the pattern, we should just list all files for these reasons:
- Tshark doesn't care about the file extension
- The user typically types a prefix before hitting Tab
- Capture files are typically stored in a directory without many other files
> Allow all file types for tshark -r

- completions/feh
Add common file extensions for farbfeld images (*.ff / *.ff.gz / *.ff.bz2) to feh completions
> Allow completion of farbfeld images in feh

- completions/Makefile.am
- completions/apt-mark
- test/t/test_apt_mark.py
- test/test-cmd-list.txt
Mostly borrowed code from `apt-get` completion. I've also added some basic tests for edge case options.
Note that I've implemented the completion to display short options as well, which I could of course remove if they are deemed unnecessary.
> New completion: apt-mark

- completions/make
FreeBSD sed does not like constructs like '\(.\{0\}\)':
> sed: 1: ...: RE error: empty (sub)expression
Omit such dirname group altogether.
Closes https://github.com/scop/bash-completion/issues/213
> make: fix sed error on FreeBSD

- completions/.gitignore
- completions/Makefile.am
- completions/mutt
- test/t/Makefile.am
- test/t/test_neomutt.py
- test/test-cmd-list.txt
The neomutt package has been in Debian since buster.
> mutt: enable completions for neomutt

- bash_completion
- completions/7z
- completions/tar
- completions/unace
- completions/unrar
Comic book archives¹ are simply archive files containing images.  While
they are typically treated as e-books and fed to programs that can
handle those, they are also plain archive files and can therefore be
manipulated by the corresponding program.
¹ https://en.wikipedia.org/wiki/Comic_book_archive
The following file extension mappings are added:
.cb7 → 7z
.cba → unace
.cbr → unrar
.cbt → tar
.cbz → unzip, zipinfo
(Note that .cbt files, unlike .tar files, are never compressed.)
> 7z, tar, unace, unrar, unzip, zipinfo: recognize comic book archives

- bash_completion
As a side effect, we no longer support avahi-browse versions without -k.
Closes https://github.com/scop/bash-completion/issues/497
> _known_hosts_real: look up _ssh._tcp from avahi, too

- bash_completion
Cygwin and MSYS2(including Git-for-Windows and MinGW64/32) respectively set `$OSTYPE` to `cygwin` and `msys`, so the current implementation of `_ncpus` calls `getconf NPROCESSORS_ONLN` when using either. However, for both cases, `getconf` only recognizes `_NPROCESSORS_ONLN`, not `NPROCESSORS_ONLN`. This simple change just makes the existing behavior for systems where `$OSTYPE` matches `*linux*` also apply to systems matching the corresponding values for Cygwin and MSYS2.
I did have someone with a Mac check what `getconf` would recognize on their machine, in case `$OSTYPE == *darwin*` should also be included, but oddly it succeeds and returns the same value for both variable names, so I don't know if there's merit in doing anything more.
> Cygwin and MSYS compat for _ncpus

- completions/screen
The original rule didn't complete from `/dev/serial/by-id/`.
It also makes sense to complete from any other directory under `/dev/serial`, as that's a logical place for custom udev rules to add symlinks for meaningful device names.
> screen: Match all files in directories under /dev/serial

- completions/Makefile.am
After https://github.com/scop/bash-completion/commit/3671cee9e0f9981b3452f1d7b459a6f3b0b2f6a2 the `declare` completion and its links were not getting installed.
> Fix install of declare completion

- bash_completion
We follow the message recent bash would output when sourcing a dir
without letting bash to do it; doing so avoids fd leaks on some older
but still supported bash versions. Other than that, let all output from
sourcing the file pass through to ease debugging.
Closes https://github.com/scop/bash-completion/issues/506
> feat(__load_completion): don't hush errors or output when sourcing files

- completions/jq
The options are not all listed by --help, so look in the man page to find a
nearly complete list (I hope!). Neither the man page nor --help mentions --help
or --version; I have not looked elsewhere to see if there might be yet more.
The treatment of -f|--from-file was incorrect: that option’s argument is the
filter, so the argument should be counted towards the total number of arguments
so far. Hence, remove --from-file from the list of options whose argument is
counted as an option.
> feat(jq): add support for all options, and fix --from-file

- completions/cvs
- test/t/test_cvs.py
I noticed 'cvs status' commands were not completing correctly. This change adds the 'status' command to the 'diff' and 'log' command cases. It is very similar to this pull:
https://github.com/scop/bash-completion/pull/194
I also added a few test cases. Thank you!
> cvs: added support for 'cvs status' completions

- test/t/conftest.py
After running `make check` or `cd test/t; pytest-3 ...`, my command histories in `~/.bash_history` were washed out. I believe we should set `HISTFILE=/dev/null` in `conftest.py` not to affect the users's history.
This time I didn't add the test for this behavior. If you think we need to add tests for tests, please let me know.
**Edit**: Resolve #321
> conftest: set HISTFILE=/dev/null in order not to affect user's history

- bash_completion
- test/t/conftest.py
- test/t/unit/test_unit_quote_readline.py
`_quote_readline_by_ref` in `bash_completion` has a problem similar to the code injection vulnerability. This PR solves the problem.
**Edit** (2021-03-16): There was already a related issue #189, so let me mark as [ Fix #189 ].
Here I describe a simple reproducer. With the following operation, a command `touch file` is unintendedly executed inside the completion function.
```bash
$ bash --rcfile bash_completion.sh
$ echo '$(touch file)[TAB]
```
In the above code block, `[TAB]` represents pressing <kbd>TAB</kbd> key. When <kbd>TAB</kbd> is pressed, the command `touch file` is executed, which can be confirmed by an unintended new file `file`.
For a more practical example (in which I noticed this problem), a file named `0.0` is created by the following operation:
```bash
awk '$1 > 0.0[TAB] …
```
> Fix unintended command execution by "_quote_readline_by_ref"

- bash_completion
- test/t/conftest.py
- test/t/unit/test_unit_quote_readline.py
This is the PR for the fix discussed in the conversation https://github.com/scop/bash-completion/pull/492#discussion_r637213822. We want to revert the following change:
```diff
-          printf -v value "$value" # Decode escape sequences of \....
+            printf -v value %s "$value" # Decode escape sequences of \....
```
I have included the tests along with the fix.
Because I need to make a test that involves a TAB character in the filenames, I would like to add this new argument to support command lines in which the actual input sequence and the result rendered to the terminal are different. For example, suppose we think about a command-line string `"echo alpha\\\tb"`:
- A. Inputs from a keyboard would be `"echo alpha\\\026\tb"` i.e., <kbd>e c h o SP a l p h a \ C-v TAB b</kbd>
- B. …
> Fix the printf unescaping in "_quote_readline_by_ref"

- test/t/conftest.py
- test/t/test_evince.py
- test/t/test_kdvi.py
- test/t/test_kpdf.py
- test/t/test_man.py
- test/t/test_tar.py
- test/t/unit/test_unit_known_hosts_real.py
- test/t/unit/test_unit_quote_readline.py
> *From https://github.com/scop/bash-completion/pull/492#issuecomment-845807416*
> > Changing `OLDPWD` isn't "allowed", changes in its value are just expected as tests may `cd` around. We could remove the special treatment for it if someone wants to land work to make that happen. `pushd` and `popd` could be an alternative.
>
> OK. If it is not too hard, maybe I'll do that after this PR is settled.
I made changes for this one. There were three places where `cd` was used to change the working directory for tests. I separated them into two commits.
One place is the `cd` into the directory created by `prepare_fixture_dir`, which was used in `test_{kdvi,kpdf,evince}`. I changed these tests to use the temporary directory created by `temp_cwd` to reduce the places `cd` is called. Now …
> test: detect unexpected OLDPWD change

- completions/_mount.linux
- completions/_umount.linux
- completions/feh
- completions/removepkg
- completions/sbopkg
- completions/slackpkg
- completions/slapt-get
- test/runLint
- test/t/conftest.py
In searching the uses of `cd` command in completions, I found that `cd` is directly called instead of through `builtin cd`. The builtin `cd` is one of the commands that users define an alias or a function (to save the visited directory, etc.). I suggest prefixing them with `builtin` keyword.
I searched for the policy of `bash-completion` on this kind of treatment and found in `CONTRIBUTING.md` the following item:
> - Use printf(1) instead of echo(1) for portability reasons, and be sure to invoke commands that are often found aliased (such as ls or grep etc) using the `command` (or `builtin`) command as appropriate.
So I think we should also apply this rule to `cd` builtin. (By the way, I found that so far no builtin commands have been prefixed by `builtin` in any completions, so `cd` is …
> completions: invoke "cd" as "builtin cd"

- bash_completion
- test/t/conftest.py
- test/t/test_man.py
This fixes the test failure of `test_man.py`. `@pytest.mark.complete(require_cmd=True)` is referenced only when the fixture `completion` is requested. Since `completion` is not requested in the new version of `test_10`, `require_cmd=True` is inactive now. This PR explicitly checks the command (non-)existence to properly skip the test.
> test(man): fix skip failure of `test_10`

- completions/Makefile.am
- completions/_slackpkg
Refs https://github.com/scop/bash-completion/pull/531
> refactor(slackpkg): deprecate in favor of upstream one in >= 15.0.4

- test/t/conftest.py
[The failure of Workflow Action `#246`](https://github.com/scop/bash-completion/actions/runs/911061422) is caused by history expansions induced by `MAGIC_MARK = "__MaGiC-maRKz!__"`. In this pull request, we remove `!` from `MAGIC_MARK` to avoid unexpected history expansions. Instead, I appended 10 characters (coming from my machine's entropy, `head -c  10 /dev/urandom | base64`).
> test(conftest): prevent MAGIC_MARK from history expansions

- test/t/conftest.py
Separate commit 53060e3 in #546
> test(conftest): support `@pytest.mark.bashcomp(required_cmd=True)`

- test/t/test_2to3.py
- test/t/test_cpan2dist.py
- test/t/test_dmypy.py
- test/t/test_isort.py
- test/t/test_jsonschema.py
- test/t/test_mypy.py
- test/t/test_pydocstyle.py
- test/t/test_pylint.py
`require_longopt=True` implies `require_cmd=True` by default.
> style(test): remove redundant require_cmd with require_longopt

- completions/xmlwf
- test/t/test_xmlwf.py
Parsing issue uncovered by https://github.com/scop/bash-completion/pull/555/checks?check_run_id=3006185602, missing -a/-b handling by observing the newer xmlwf output.
> xmlwf improvements

- test/t/conftest.py
- test/t/test_convert.py
- 2548107a I'd like to let `assert_complete()` check that no error messages are output while the completion. This would be used in the next PR for the fix of the `scp` completion.
- 1c354b3a It detected an error message in `test_2` (`test_convert.py`) that has been missed before.
> test(conftest): check error messages in `assert_complete()`

- .github/workflows/check.yaml
Avoids running twice for pull requests whose source branch is in this
repo.
> ci(github): run pushes only on master

- .pre-commit-config.yaml
Running from flake8 only checks for modifications, while the standalone
one takes care of writing its changes too, avoiding one human step in
the process.
> test(pre-commit): use separate isort hook

- renovate.json
Similarly as for black and flake8 already.
> ci(renovate): group isort updates, mark as PEP 440 versioned

- bash_completion
- test/t/test_ssh_add.py
- test/t/test_ssh_keygen.py
- test/t/unit/test_unit_parse_help.py
- test/t/unit/test_unit_parse_usage.py
This is another fix of `_parse_help` and `_parse_usage` caused with `shopt -s failglob` or `shopt -s nullglob`.
```bash
$ shopt -s failglob
$ ssh-keygen -[TAB]bash: no match: -?
bash: no match: -?
```
With `nullglob`, it hangs:
```bash
$ shopt -s failglob
$ ssh-keygen -[TAB] # --> no response to subsequent user inputs until the user presses [C-c]
```
> fix(_parse_help): protect custom help options from pathname expansions

- bash_completion
- test/t/unit/test_unit_parse_help.py
This solves error messages on the standard option completions under `shopt -s failglob`. For example, with `shopt -s failglob`, we see the following error message:
```bash
$ shopt -failglob 
$ tar -[TAB]bash: no match: --occurrence[=NUMBER]
```
> fix(_parse_help): protect word splitting from pathname expansions

- completions/ssh
- test/t/test_scp.py
This is a PR to fix the problem reported at https://github.com/akinomyoga/ble.sh/issues/123
With `shopt -s nullglob` or `shopt -u failglob`, the completion for `scp` fails and produces error messages on the command line.
Proper quoting is needed. To prepare the corresponding unit tests, I first created a PR #555 to support checks of error messages in `assert_complete()` (`test/t/conftest.py`). I'll open this PR as a Draft PR until #555 is processed.
> fix(scp): fix nullglob/failglob errors

- bash_completion
- completions/_op
- completions/crontab
- completions/cvs
- completions/dpkg
- completions/find
- completions/info
- completions/lvm
- completions/modprobe
- completions/protoc
- completions/qdbus
- completions/tar
- test/runLint
- test/t/conftest.py
- test/t/test_ls.py
- test/t/unit/test_unit_expand.py
- test/t/unit/test_unit_expand_tilde_by_ref.py
- test/t/unit/test_unit_filedir.py
- test/t/unit/test_unit_init_completion.py
- test/t/unit/test_unit_ip_addresses.py
- test/t/unit/test_unit_known_hosts_real.py
- test/t/unit/test_unit_pgids.py
- test/t/unit/test_unit_pids.py
- test/t/unit/test_unit_pnames.py
- test/t/unit/test_unit_quote_readline.py
- test/t/unit/test_unit_tilde.py
- test/t/unit/test_unit_xinetd_services.py
I describe the detail in the commit message of each commit.
> Explicitly specify `unset` types / Adjust uses of temporary global variables

- .pre-commit-config.yaml
So we don't have to repeat `stages: [commit]` for almost all checks.
> chore(pre-commit): make use of `default_stages` in commit

- completions/ip
…t/commit/?id=f19966efeedf5292f003aaccecc3ac3a8a069b28
ip netns list output has change, it's now look like this
ip netns list
netns12 (id: 1)
netns45 (id: 0)
> fix ip netns list parsing

- bash_completion
- test/t/unit/test_unit_command_offset.py
This pull request addresses a problem that occurs when `_command_offset` is being executed (e.g. when using sudo), and a completion function exists already. When this function signals that completion should be retried (changes compspec and exits with status 124), completion is not attempted again.
> Handle compspec changes during meta-command completion.

- completions/ssh
- test/t/test_ssh.py
Options that take an arg must not be treated as arg the _count_args way.
Closes https://github.com/scop/bash-completion/issues/647
> fix(ssh): don't confuse arg counting with option args

- bash_completion
- test/t/unit/test_unit_expand.py
> Fix `_expand` for failglob

- completions/info
- completions/man
I've made the changes mentioned in #670.
> fix(man,info): remove ineffective "_expand" calls

- doc/styleguide.txt
I have noticed that `doc/*.txt` are actually AsciiDoc, and some of the formatting in the HTML file `doc/html~/main.html` generated by `./makeHtml.sh` is broken. This PR fixes the formatting.
> doc(styleguide): fix asciidoc format

- completions/ssh-keygen
- test/t/test_ssh_keygen.py
The man page is missing bunch of equal signs for FIDO options that take an argument.
> feat(ssh-keygen): sync -O options with openssh 8.4p1, FIDO arg fixes

- README.md
- completions/tar
- doc/bash_completion.txt
While working on #678, I noticed we have some redundant and inaccurate descriptions in README for some variables. I'm sure some of these are not FAQ's these days any more either.
This removes the redundant descriptions from README, moves it elsewhere for `tar`, and generally makes the info a bit less scattered. I think we should make the main README.md even smaller going forward, but that's something for another PR.
> Remove redundante variable docs from README

- completions/feh
(trivial change)
`feh` (as well as ImageMagick) has been supporting WebP for a while now. WebP has already gained much traction as a successor to PNG and JPEG, so it’s important than completion lets us open them. :-)
> feat(feh): complete on WebP images

- bash_completion
- completions/7z
- completions/_umount.linux
- completions/svcadm
- test/t/unit/test_unit_unlocal.py
From the bash man page:
Word Splitting
...snip...
The shell treats each character of IFS as a delimiter, and splits the
results of the other expansions into words using these characters as
field terminators.  If IFS is unset, or its value is exactly
<space><tab><newline>, the  default, then  sequences of <space>, <tab>,
and <newline> at the beginning and end of the results of the previous
expansions are ignored, and any sequence of IFS characters not at the
beginning or end serves to delimit words.  If IFS has a value other than
the default, then sequences of the whitespace characters space, tab, and
newline are ignored at the beginning and end of the word, as long as the
whitespace character is in the value of IFS (an IFS whitespace
character).  Any character  in  IFS that is not IFS …
> Properly handle environments with unset IFS

- completions/rsync
- test/t/test_rsync.py
- test/test-cmd-list.txt
Hi,
I often need this option and I find the name rather long, it would be nice to have it completed.
In order to limit the size of the diff, I didn't try to optimize the layout of the options in the `COMPREPLY` variable. Let me know if that is a problem.
> rsync: improve completion by using _parse_help

- completions/_umount.linux
This removes some ineffective `IFS` settings found in #687 like the following:
```bash
local IFS=$'\0'
COMPREPLY+=("$fs_label")
_comp_unlocal IFS
```
First of all, the value `"$fs_label"` is quoted so that the word splitting is disabled. So the behavior doesn't change by changing `IFS`. Next, Bash doesn't allow storing NUL in the variable, so `IFS=$'\0'` actually results in an empty value `IFS=''`.
I'm not sure what has been the original intent of setting NUL to `IFS`. I have checked the change history. This `IFS` setting was originally introduced in commit [`99b2894`](https://github.com/scop/bash-completion/commit/99b289474ead02cc8c629ceec1192ce9f0b4f84e#diff-a33e10856930590d5777b4de609f66b088b7477e930a200bb2439e83724ef328L51-R87). At that time, the code looked like
```bash
IFS=$'\0' …
```
> fix(_umount.linux): remove unnecessary IFS setups

- test/docker/ubuntu14/Dockerfile
deadsnakes packages for Ubuntu 14.04 and 16.04 no longer exist, switch to portable Pyston 2.3.1. Go with Pyston instead of PyPy for (hopefully) better compatibility with CPython.
- https://github.com/deadsnakes/issues/issues/195
- https://github.com/scop/bash-completion/runs/4995567978?check_suite_focus=true#step:4:548
The primary reasons Ubuntu 14 is still kept around in the test matrix are that it's our only bash 4.3 environment at the moment, and it's nice to be able to test against various older versions of tools -- the coverage with e.g. CentOS 7 isn't as big.
> test(ubuntu14): switch Python to Pyston 2.3.1

- renovate.json
The config:base preset sets it to 10. That's a tad low when one
intentionally keeps bumps open (to reduce churn), for example until
they break something or a release is imminent.
> chore(renovate): allow 20 concurrent PR's

- bash_completion
- completions/cvs
- completions/invoke-rc.d
- completions/update-rc.d
Ref. https://github.com/scop/bash-completion/pull/729#issuecomment-1097211746
Also includes the change of an initialization-function name.
> refactor(bash_completion): rename internal/initialization variables

- bash_completion
- completions/_rtcwake
- completions/_yum
- completions/dpkg
- completions/hcitool
- completions/hunspell
- completions/ipmitool
- completions/lintian
- completions/minicom
- completions/mysql
- completions/ps
- completions/qemu
- completions/screen
- completions/valgrind
- completions/vpnc
- completions/xdg-mime
- test/t/conftest.py
- test/t/unit/test_unit_expand_glob.py
Fixes #705 and similar problems
Pathname expansions are used in many places in the codebase, but it seems only a small part of these pathname expansions considers the setting of `nullglob`, and only `mysql` considers the setting of `failglob`. All the pathname expansions except for that in `mysql` can possibly fail due to `failglob`. Actually, there are even other settings that we need to care about for the pathname expansions, such as `nounset`, `dotglob`, `GLOBIGNORE`, and `nocaseglob`.
We don't want to always write codes to check all these settings in-place, so I suggest introducing a shell function `_comp_expand_glob` to perform the pathname expansions.
This PR contains several changes.
- ecc384df This is an extension to `conftest.py (bash_env_saved)` that allows an arbitrary change …
> feat(_comp_expand_glob): Add a utility to safely perform pathname expansions (Fix #705)

- bash_completion
- doc/configuration.md
- test/config/bashrc
I'm not sure what is the most appropriate way to solve the issue, but let me explain the issue here.
Fedora (and probably its downstream RHEL and CentOS) has `/etc/bash_completion.d/redefine_filedir` which tries to overwrite the shell function `_filedir` with the version defined in `/usr/share/bash-completion/bash_completion`. This doesn't cause the problem as far as the user uses the distribution version of `bash-completion` in `/usr/share`. However, if one downloads and uses the latest version of `bash-completion`, this introduces the inconsistency because `_filedir` in `redefine_filedir` is not necessarily the same as the downloaded version.
The reason why Fedora tries to overwrite `_filedir` is explained in `/etc/bash_completion.d/redefine_filedir`:
```
#
```
Actually, its  workaround …
> Disable `/etc/bash_completion.d/redefine_filedir`

- bash_completion
- completions/aptitude
- completions/arch
- completions/dpkg
- completions/ifup
- This is still a draft; only a small part of the functions are processed.
- This is based on #734 (`_comp_xfunc`)
- I open this PR to reference the related PRs because some of my existing branches already contain some part of refactoring names and behaviors, so I'd like to process them at the same time.
> refactor(bash_completion): rename functions `_userland`, `_sysdirs`, `_have`, and `_rl_enabled`

- completions/evince
Years ago, evince used to display many different image formats.  I
don't think it does any more.
I'm running evince 42.2 from debian testing/unstable.
I tested this with a simple image (`/usr/share/icons/cab_view.png`) and
imagemagick's "convert" tool like so:
```sh
suffixes="gif jpg png pnm pbm pgm ppm bmp xpm ico xwd tga pcx tiff miff"
for x in $suffixes; do
convert cab_view.png cab_view.$x
evince cab_view.$x
done
```
For all of the formats listed above except for "tiff", evince reports
"Unable to open document: …", and "File type … is not supported"
So i've removed those image formats from the evince tab completion.
----
(edited to add: i also tried with graphicsmagick's `gm convert` tool, with the same results, except that graphicsmagick wasn't able to convert to `.ico`)
> Drop unsupported formats from evince.

- bash_completion
- completions/_umount.linux
- completions/export
- completions/make
- completions/mutt
- completions/pkgadd
- completions/pkgutil
- completions/ssh
- test/t/unit/test_unit_dequote.py
- test/t/unit/test_unit_quote.py
In #735, I'd like to refactor the function names `quote` and `dequote`, but another branch that I created two months ago contains an improved version `_comp_dequote` and improved uses of `quote`, so I'd like to process this branch before #735 if possible.
> refactor(bash_completion): refactor `{ => _comp_}{dequote,quote}`

- bash_completion
- test/t/unit/test_unit_get_cword.py
Without this commit, the cword calculation is done wrongly if there is only whitespace after the caret, but no additional word.
I tried to execute the tests and add a test for this, but unfortunately I was not able to get the test to work properly and didn't really get how to write tests properly in this project.
So it would be nice if the reviewer could execute the tests to see whether my change breaks anything else tested and maybe someone can also add a test for this.
> Fix __reassemble_comp_words_by_ref with only space after caret

- completions/7z
These were added to the help output of p7zip 15.09 and are present in all versions of 7zz.
Thanks,
Kevin
> feat(7z): complete h i and rn commands

- completions/.gitignore
- completions/7z
- completions/Makefile.am
p7zip provides [7zr(1)] in addition to [7za(1)] and [7z(1)].  7zr behaves like 7z with the exception that it only supports the 7z, LZMA, and XZ formats.
Since [7-Zip 21.01 alpha], the 7-Zip project provides a command-line version of 7-Zip for Linux, [7zz(1)].  It shares nearly all of the command-line options and syntax of the p7zip port.
This PR applies the current completions for 7z to 7zr and 7zz.
**Note:** There are a few minor differences between 7zz and the others (e.g. 7zz does not support `-mh*` or `-ms*`) which will can be addressed by subsequent work.
Thanks for considering,
Kevin
[7-Zip 21.01 alpha]: https://sourceforge.net/p/sevenzip/discussion/45797/thread/d401ab2966/
[7z(1)]: https://github.com/jinfeihan57/p7zip/blob/v17.04/man1/7z.1
[7za(1)]: …
> Add support for 7zr and 7zz

- README.md
The function is `command_not_found_handle` (no trailing `r`).
Be somewhat more specific how to implement a well behaving/cooperating one.
> docs(README): elaborate and typofix command_not_found_handle FAQ item

- bash_completion
- test/t/unit/test_unit_init_completion.py
Fixes #769 
This is still draft because I haven't added tests and also haven't tested it carefully.
> fix(_init_completion): update redirection pattern

- completions/kldload
Current completion only shows modules from `/boot/kernel/`. There are more directories with modules now in FreeBSD e.g. local modules go usually to `/boot/modules/`. Looks like all current directories are written in `sysctl` variable `kern.module_path` (see also `kldconfig(8)`). New implementation considers all these paths.
I'm not experienced in bash programming so there can be some bugs. Tested on FreeBSD 12.3.
> Add more module dirs to kldload

- bash_completion
- completions/apt-get
- completions/gdb
- completions/kldload
- completions/man
- completions/pydoc
- completions/pylint
- completions/removepkg
- completions/rpm
- completions/ssh
- completions/vpnc
- test/t/unit/test_unit_looks_like_path.py
Be more consistent with how we test this across the tree.
`apt-get`, `gdb`, `kldload`, `pydoc`, `pylint`, `removepkg`, `rpm`, `scp`, and `vpnc` gained better recognition of various kinds of paths as the result.
> feat(_comp_looks_like_path): new utility, use it

- bash_completion
ca361be02a92e30a3d26d376b30faf268853e836 enables warnings about trying to source directories when loading completions. That's useful, but triggers the errors in the common case of trying to source something, `. `<kbd>Tab</kbd>
Special case `.` (and for completeness, even though not that interesting, `..`) so we don't issue the warning about them.
> fix(__load_completion): do not warn when completing `.` first time

- test/t/Makefile.am
- test/t/unit/Makefile.am
- test/t/unit/test_unit_expand_glob.py
I noticed that the tests in #793 and #791 are actually not run in CI. I found that also other files are not included in `Makefile.am`.
> test(Makefile.am): update EXTRA_DIST in Makefile.am

- bash_completion
Refs. https://github.com/scop/bash-completion/discussions/539#discussioncomment-3000762 and #731
> refactor(_comp_expand_glob): follow API naming for exporter functions

- bash_completion
- test/t/unit/test_unit_command_offset.py
Extracted from ~~#790~~ #791. This is also actually independent.
> - d2c0b4ee **simplify logic**: The original code tries to manually perform a string manipulation that can be achieved by a single parameter expansion. Also, it tries to manually perform the array compaction that can be achieved by a single parameter expansion. The behaviors of the new codes slightly differ from the original ones, but I believe the behaviors of the new codes are better:
>   - In the original code, `COMP_LINE` becomes empty when `${COMP_WORDS[i]}` is not contained in `$COMP_LINE`, though I don't think that happens as far as these variables are modified by external codes. In the new code, such a word `${COMP_WORDS[i]}` is just ignored.
>   - In the original code, the words in `COMP_WORDS` after `COMP_CWORD` …
> refactor(_command_offset): refactor the adjustment of `COMP_WORDS`

- completions/gzip
`--alias`/`-A`, `--comment`/`-C`, `--iterations`/`-I`, `--maxsplits`/`-J`. These do not seem to conflict with ones gzip has.
> feat(pigz): add more option argument non-completions

- test/config/bashrc
- test/t/conftest.py
Extracted from #791. Actually, this change is needed for #791, but @scop seems to be going to agree with merging this first, I separate the change here.
> - 973276a5 **ignore mut variables in diff_env (conftest)**: I'd like to cache the regular expressions constructed from `COMP_WORDBREAKS` in c59655c4. This means that the variables that hold the cache can be changed while completions, so they should be excluded from the `diff_env` test of the test suite.
>   - Failing approach: I tried to implement it by `ignore_env` or by adding the variable names in [this line](https://github.com/scop/bash-completion/commit/973276a5397daf764f0911f7a9713ec530ea7c66#diff-191cf488d891a8f1d47930268d94548184bfdf58c7cb898d59327e757c83be2bL731), but it seems to fail because the variable contains newlines so …
> test(conftest): exclude cache variables for `diff_env`

- bash_completion
I separate the change from ~~#790~~ #791. This is the most independent part.
> - 868e98ea **work around localvar_inherit**: This is actually not directly related to the refactoring of `_command_offset`, but I noticed this in investigating which variables can be modified by `_comp_offset` for 868e98ea. The implementation of `_get_comp_words_by_ref` assumes that the declared variables `vcur`, `vwords`, `vcword`, and `vprev` have initially unset values to later test them with `[[ -v vcur ]]`, etc., but this is not ensured when `localvar_inherit` is turned on.
The description is unchanged from that in ~~#790~~ #791.
> fix(_get_comp_words_by_ref): work around localvar_inherit

- bash_completion
- completions/_ionice
- completions/ccache
- completions/find
- completions/gdb
- completions/screen
- completions/strace
- completions/sudo
- completions/timeout
- completions/valgrind
- completions/watch
- completions/xvfb-run
- test/t/unit/test_unit_command_offset.py
Extracted from #791.
> - cd98abd8 **move `_command`**: This just moves the position of the function. I think `_command_offset` had been sufficiently short before but now is a long function, so it shouldn't be put between `_command` and `complete -F _command` any more.
> - 15c699fd **rename `{ => _comp}{_command_offset,_command,_root_command}`**: Naming convention suggested by #539.
The description is unchanged.
> refactor(_command_offset): rename `{ => _comp}{_command_offset,_command,_root_command}`

- bash_completion
- completions/Makefile.am
- completions/help
- test/t/Makefile.am
- test/t/test_help.py
The simple `-A helptopic` completion for does not support completion of options, and does not do a too good job with items containing parens, such as `(( ... ))` and `foo ((`.
> feat(help): support options, improve quoting

- bash_completion
- test/fixtures/_known_hosts_real/config_include
> fix(_known_hosts_real): exclude directories from the config files

- completions/complete
> refactor(compgen,complete): parse options from `help -s` output

- completions/bind
- completions/declare
- completions/export
- completions/pwd
- completions/ulimit
Instead of relying on undocumented `--help` or `--usage` behavior.
> refactor(builtins): parse options from `help -s` output

- test/t/conftest.py
`assert_complete_at_point` does not properly clean up the command line. This may cause the failure of subsequent tests. The same cleanups as `assert_complete` should be performed for `assert_complete_at_point`. Instead of repeating the cleanup code in `assert_complete_at_point`, I have merged the special treatment of `assert_complete_at_point` in `assert_complete` as suggested in a `TODO` in the code comment. The *unintended* test failures in #810 and #811 are fixed by this PR.
> test(conftest): merge `assert_complete_at_point` to `assert_complete`

- bash_completion
- test/t/unit/Makefile.am
- test/t/unit/test_unit_split.py
I have three branches depending on this new utility (the branch of #696, and unsubmitted [akinomyoga/failglob-1](https://github.com/scop/bash-completion/compare/master...akinomyoga:failglob-1?expand=1) and [akinomyoga/failglob-3](https://github.com/scop/bash-completion/compare/master...akinomyoga:failglob-3?expand=1). I would like to have this utility merged first to avoid complicated dependency handling.
> feat(_comp_split): add a function to split a string into an array

- completions/fio
- test/t/test_fio.py
The majority of options are actually not available from `--help`, but rather `--cmdhelp=all`.
Support some option arguments "natively", some per `--cmdhelp=COMMAND` output, and engines from `--enghelp` output.
> feat(fio): more option and arg completions

- bash_completion
- test/t/test_cd.py
- test/t/test_pushd.py
For both of these, `help -s` output is such that `_parse_usage` doesn't do a terribly good job with it. Parse the `help` (no `-s`) output with `_parse_help` instead.
> feat(cd,pushd): add option completion support

- completions/dpkg
Instead of piping one grep to another, then piping that to awk, simply make one call to awk with appropriate matching. This makes the completion slightly more efficient (only one process is spawned instead of three), and removes a dependency on GNU grep's non-standard -A and -B options.
> refactor(dpkg): replace grep|grep|awk with pure awk

- bash_completion
Included with the ldns library, the drill tool is similar to dig and is used for DNS lookups. As such, it greatly benefits from host completion.
> feat: set up drill to be completed by _known_hosts

- .typos.toml
Unfortunately `typos` lacks ability to filter out false positives on per file (or line) basis at the moment, so we end up going global with all exclusions.
> chore(typos): add config, filter out false positives

- bash_completion
- test/t/unit/test_unit_command_offset.py
Bash 5.2 starts to quote the command name in `complete -p` if necessary.
> fix(_command_offset): support quoting of the command name in `complete -p` (bash 5.2)

- .pymarkdown.json
- CONTRIBUTING.md
- doc/api-and-naming.md
- doc/styleguide.md
- https://github.com/scop/bash-completion/discussions/537
- https://github.com/scop/bash-completion/discussions/539
> docs: add API and naming

- completions/xdg-mime
Broken by https://github.com/scop/bash-completion/pull/827#discussion_r1031166072
> fix(xdg-mime): mime type array index expansion

- completions/reportbug
- test/t/test_reportbug.py
Closes https://github.com/scop/bash-completion/pull/753
It's unfortunate that the help output goes to stderr, but I suppose this is good enough.
> feat(reportbug): parse various option args from option help

- completions/jq
`jq` support `jsonl` files just as well as plain JSON, so this just adds support for that file extension. This follows the pattern I saw in other completions, though it is my first commit here, so just let me know if something is off (or change it). 
I am not sure this counts as a "feature" but no other prefix seemed obviously appropriate.
> feat(jq): support jsonl files as well as json

- completions/openssl
Add `storeutl` to commands list. [Man page](https://www.openssl.org/docs/man1.1.1/man1/openssl-storeutl.html) says this command was added in OpenSSL 1.1.1.
> feat(openssl): recognize `storeutl`

- completions/make
- test/fixtures/make/test2/Makefile
- test/t/test_make.py
Resolve #544 
- Commit 53060e3b: support `@pytest.mark.bashcomp(required_cmd=True)` to skip all the tests in the class.
- Commit eb12832c: add failing test cases to illustrate the problems
- Commit 0ddae4c1: do not strip directory names when `COMP_TYPE=37`. This happens when the user presses <kbd>TAB</kbd> under the readline setting `bind 'set show-all-if-ambiguous on'` is set.
- Commit d5181c55: complete subdirectories as far as the path is unique
The test `test_github_issue_544_4` (`test_make.py`) currently fails because of the design of the test suite. The test suite extracts the generated completions by changing the readline settings as
```diff
@@ -22,20 +22,20 @@
set menu-complete-display-prefix off
set meta-flag on
set output-meta on
-set page-completions on
+set page-completions …
```
> fix(make): fix stripped directory names with `bind 'set show-all-if-ambiguous on'`

- test/deprecated/update-deprecated-links
- test/runLint
- test/update-test-cmd-list
The description is in the commit message 36573340e0f06b1da97bfb0ff2aa2596a3871b1a.
> chore(pre-commit/update-deprecated-links): exclude untracked files

- Makefile.am
- bash_completion
- bash_completion.d/000_bash_completion_compat
- doc/configuration.md
- test/config/bashrc
As discussed at https://github.com/scop/bash-completion/discussions/537#discussioncomment-3613857
Draft/TODO:
- ...probably some more
> refactor: ship depreated things in a separate file

- .pre-commit-config.yaml
- bash_completion
- bash_completion.d/000_bash_completion_compat
- completions/ssh
- completions/xsltproc
- test/t/test_umount.py
- test/t/unit/Makefile.am
- test/t/unit/test_unit_filedir.py
- test/t/unit/test_unit_get_comp_words_by_ref.py
- test/t/unit/test_unit_get_words.py
- test/t/unit/test_unit_ip_addresses.py
I had some pending changes for the naming convention in `bash_completion`, but let me submit it now.
One thing that I haven't yet decided is whether to strip `_by_ref` from the new names or not. I think the suffix `_by_ref` is added to differentiate them from the older versions that output the result to stdout. Now we deprecated these older versions and wouldn't try to prepare the new names `_comp_*` for these deprecated functions, so there is no need for the differentiation anymore. But perhaps it might still be better to keep the suffix to remind us of the unique convention of these functions that receive variable names in the arguments.
> refactor(bash_completion): rename `_get_comp_words_by_ref`, etc.

- test/runLint
Problematic because it can cause keybindings to change.
https://github.com/scop/bash-completion/issues/190
As we are not running `runLint` automatically and we aren't clean per its checks anyway, this won't be catching all of it. But I guess it's better than nothing.
> test(runLint): add check for touching POSIX mode

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- test/t/unit/Makefile.am
- test/t/unit/test_unit_quote_compgen.py
- Also, `quote_readline` is deprecated.
- `_comp_quote_compgen` always stores the result in `ret` (as in the second paragraph in [§ General API conventions](https://github.com/scop/bash-completion/blob/master/doc/api-and-naming.md#general-api-conventions)).
After this is merged, I'll submit the refactoring mentioned in https://github.com/scop/bash-completion/pull/909#issuecomment-1488328631.
> refactor: rename `_quote_readline_by_ref => _comp_quote_compgen`

- bash_completion
- completions/ccze
- completions/complete
- completions/crontab
- completions/curl
- completions/cvs
- completions/dpkg
- completions/hunspell
- completions/ipmitool
- completions/lintian
- completions/minicom
- completions/mplayer
- completions/mysql
- completions/nslookup
- completions/pkg-get
- completions/pkgadd
- completions/pkgutil
- completions/rpm
- completions/screen
- completions/ssh
- completions/tipc
- completions/tune2fs
- completions/update-rc.d
- completions/vpnc
- completions/wodim
There are also other fixes I noticed while rewriting `compgen -W '${arr[@]}'`. The descriptions are found in the commit messages.
> refactor(completions/*): ensure quoting for `compgen -W '${arr[@]}'`

- completions/_nox
Fix discussed in https://github.com/scop/bash-completion/pull/917#discussion_r1161092667
The description is in the commit message.
> fix(nox): improve the PATH manipulation

- bash_completion
We don't actually know if filenames are wanted here, so there's no reason to insist filename completions specifically. Besides, the bash and readline defaults handle the basic filename completions at least as well as we do. They additionally make wildcard completions work.
Remove no longer needed long option splitting, as it is no longer needed after this change.
Closes https://github.com/scop/bash-completion/issues/444
> fix(_minimal): fall back to defaults instead of `_filedir`

- bash_completion
- test/t/unit/Makefile.am
- test/t/unit/test_unit_compgen.py
Now we have a utility function `_comp_split` to safely split strings (including the output of the `compgen` builtin and other commands) without being affected by pathname expansions, unexpected word splitting, etc. I would like to switch from the repeated `local IFS=... reset=$(shopt -po noglob); set -o noglob; ...; IFS=$' \t\n'; $reset` to `_comp_split`.
- b46b71e7 I modified `_comp_split` to return whether nonzero elements are produced in the exit status. This is because `((${#arr[@]}))` is tested in many cases after splitting strings.
- f8a8f9f6 Also, there are many cases of `_comp_split -l arr "$(compgen ARGS)"`, so it is useful to define a function `_comp_compgen arr ARGS` (in particular to reduce nested quoting and command substitutions).
- bf37c0d91cd1bd933b152174a75d9a9580976ebd …
> fix(bash_completion): use `_comp_split` and new `_comp_compgen` for safer splitting

- completions/ssh
As reported by a Debian user in https://bugs.debian.org/1033642, ssh changed the option name from PubkeyAcceptedKeyTypes to PubkeyAcceptedAlgorithms. The old name still works, but no longer presented in the manpages.
Does this pull request make sense? It's been a while since I last submitted something here, but I noticed that many things changed, so I might me making some mistakes with the submission.
> fix(ssh): deprecated option PubkeyAcceptedKeyTypes

- bash_completion
- completions/info
- completions/man
- completions/ri
- test/t/test_info.py
- test/t/test_man.py
For the problem of the code execution, see the test 74d837e456a7be230908b52de098011db2823ef6. The change of the fix is explained in the commit message of 8b12bf82c27bd7085f2249adea873c6a2761871b. The third commit e7e84d475b3497142d44446c0dbd7d42f0e5e87b contains fixes for failglob, IFS, etc., and refactoring.
> fix(man,info): avoid unexpected code execution and add failglob fixes

- bash_completion
- test/t/test_pgrep.py
- test/t/test_ssh_keygen.py
- test/t/test_tox.py
- test/t/test_tshark.py
- test/t/unit/Makefile.am
- test/t/unit/test_unit_delimited.py
Fixes #552.
Previously prefix was only prepended if COMPREPLY only contained one argument - this commit fixes it so prefix is prepended to all arguments.
The problem existed since 4138714c, in the very first version of `_comp_delimited` function. I'm not sure why the original only prepended the prefix back when there was only one completion, so I'm worried I'm missing something.
> fix(_comp_delimited): prepend prefix to all compreply args

- .gitlint
Per rationale at
https://jorisroovers.com/gitlint/#merge-fixup-squash-and-revert-commits
> ... these are temporary commits that will be squashed into a
> different commit, ...
> chore(gitlint): ignore fixup and squash commits

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/.gitignore
- completions/Makefile.am
- completions/cd
Not sure why this was left embedded in `bash_completion`.
> refactor(cd): move to `completions/`, rename `_cd` -> `_comp_cmd_cd`

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/ccache
- completions/find
- completions/timeout
- completions/valgrind
- completions/xvfb-run
- test/t/unit/test_unit_command_offset.py
Fixes #722.
This fixes it the other way around as #802. Now `_comp_command_offset` receives the index in `words` instead of that in `COMP_WORDS`.
> fix(_comp_command_offset): fix offset mismatching for words vs COMP_WORDS (use words)

- completions/curl
- test/t/test_curl.py
`_parse_help` only takes a single parameter (which is then splits) for the options that it invokes the tool with, so `curl` was being invoked with just `--help`, not with `--help all`.
> curl: fix option listing in newer versions

- completions/_adb
- completions/_udevadm
- completions/badblocks
- completions/complete
- completions/gnokii
- completions/postfix
These are small but non-trivial changes/fixes that I would like to apply before we change the interface of `_parse_{help,usage}`.
> fix: add misc fixes before `_parse_{help,usage}` changes

- completions/.gitignore
- completions/Makefile.am
- completions/_flamegraph
- completions/_mdbook
- completions/_tokio-console
- test/fallback/completions/Makefile.am
- test/fallback/completions/flamegraph
- test/fallback/completions/mdbook
- test/fallback/completions/tokio-console
See the `clap_complete` entry at https://github.com/scop/bash-completion/wiki/Externally-available-completions#fallback-3rd-party-completions -- this adds loaders for a handful of the most downloaded ones. Quite a few of them seem to provide completions as build time generated snippets only, that's why the "gaps".
> feat: add some clap_complete based 3rd party loaders

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/apt-cache
- completions/apt-get
- completions/asciidoc
- completions/cvs
- completions/iconv
- completions/list_lists
- completions/mysql
- completions/python
- completions/rpm
- completions/ssh
- doc/api-and-naming.md
- doc/configuration.md
- test/t/unit/test_unit_deprecate_func.py
Closes https://github.com/scop/bash-completion/issues/893
Closes https://github.com/scop/bash-completion/issues/963
> chore: since/deprecation versioning 

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/2to3
- completions/_modules
- completions/_mount.linux
- completions/_slackpkg
- completions/_umount.linux
- completions/bts
- completions/bzip2
- completions/cppcheck
- completions/feh
- completions/flake8
- completions/gzip
- completions/isort
- completions/lrzip
- completions/lzip
- completions/make
- completions/pylint
- completions/pytest
- completions/removepkg
- completions/sbopkg
- completions/slapt-get
- completions/xdg-mime
- completions/xz
- test/t/unit/test_unit_compgen.py
These are the cases where I modified interfaces of existing functions.
Some involve internal generators, but I haven't applied the possible suggested internal generator syntax `_comp_compgen -i CMD NAME` in https://github.com/scop/bash-completion/discussions/962#discussioncomment-5832685. If the syntax would be finally employed,  I'll update them in a future separate PR.
> fix: use `_comp_compgen` with API changes

- test/t/test_dcop.py
It's highly unlikely that a DCOP server would be running in containers.
> test(dcop): skip if basic invocation errors out

- test/t/test_dpkg_query.py
For example with an empty cache it does.
> test(dpkg-query): xfail if `apt-cache show` fails

- completions/ssh
Another issue uncovered by work on #979
> fix(scp): `nounset` mode error on unknown suboption, bash 4.2

- completions/rsync
- completions/ssh
- completions/sshfs
xfuncs being part of the API, we don't want to expose the implementation detail that the `scp` completion currently resides in the `ssh` file.
Originally part of #967
> refactor(ssh): remove `ssh` from `scp` xfunc names

- completions/7z
- completions/curl
- completions/koji
- completions/lspci
- completions/medusa
- completions/pgrep
- completions/pydoc
- completions/reportbug
- completions/tar
Before applying `_comp_compgen_split` mentioned in https://github.com/scop/bash-completion/issues/958#issuecomment-1537214890, I would like to add the following fixes that are overlapping with it.
> fix: add misc fixes before `_comp_compgen_split`

- completions/aspell
- completions/carton
- completions/iconv
- completions/mysql
- completions/perl
- completions/pydoc
- completions/pylint
- completions/pytest
- completions/python
- completions/rpm
- completions/ssh
- completions/ssh-copy-id
- completions/ssh-keygen
https://github.com/scop/bash-completion/discussions/959
> refactor: adjust to util/xfunc primary command convention

- completions/add_members
- completions/apt-cache
- completions/apt-get
- completions/arch
- completions/change_pw
- completions/check_db
- completions/clone_member
- completions/config_list
- completions/find_member
- completions/inject
- completions/list_admins
- completions/list_members
- completions/list_owners
- completions/newlist
- completions/perl
- completions/remove_members
- completions/rmlist
- completions/ssh
- completions/sync_members
- completions/withlist
Remaining found cases as mentioned in https://github.com/scop/bash-completion/pull/965#issuecomment-1558479426
> refactor: more util/xfunc primary command convention adjustments

- CONTRIBUTING.md
- doc/styleguide.md
Resolve #932 
Note: `shfmt` tries to remove the quoting of `[[ "$*" ]]`, which is needed to avoid the behavior change in bash 4.2 => 4.3. There is a similar problem with `[[ "${arr[*]}" ]]`. Actually, the current codebase doesn't have cases of `[[ "$*" ]]` or `[[ "${arr[*]}" ]]` where `shfmt` tries to remove the necessary quoting. But this could conflict in the future.
> doc: add rules for quoting

- completions/pytest
For example, one of `--vcr-record`'s arg choices is `new_episodes`.
> fix(pytest): do not filter underscores from parsed option arg choices

- bash_completion
- doc/api-and-naming.md
- test/fixtures/_comp_compgen/completions/compgen-cmd1
- test/fixtures/_comp_compgen/completions/compgen-cmd2
- test/t/unit/test_unit_compgen.py
Document the naming rules and implementation advices for xfuncs and `_comp_compgen_NAME`
https://github.com/scop/bash-completion/pull/954#discussion_r1186805078
https://github.com/scop/bash-completion/pull/964
https://github.com/scop/bash-completion/discussions/962#discussioncomment-5832685
Note: `_comp_compegn [-i CMD|-x CMD]` are not yet impl;emented.
> doc(api-and-naming): add rules for xfuncs and generators

- CONTRIBUTING.md
- bash_completion
- completions/bzip2
- completions/cd
- completions/config_list
- completions/cpio
- completions/gzip
- completions/ipmitool
- completions/java
- completions/kldload
- completions/koji
- completions/list_members
- completions/lzma
- completions/qemu
- completions/rpm
- completions/ssh
- completions/upgradepkg
- doc/api-and-naming.md
This is the final round for the `_comp_compgen` rewrite.
- 76b572650f224e2e3b85918944af0bc8dfb49952, 7261319e6c320f7a33185e3819d8f668bdcee363, 7b2dc13e4fcb28bed335bcaebfab3b042abbc1b2, and 7920c9dbe46bd5ad0a92e78b744f00ffe8b14e76 are pre-changes.
- 81adc6ce741f69e936dfb0e1e891c372341814f2, 89e3eae9eeab564b426fd356e453d299415c38ac, 9a5ed03264c0a0f94f46eb12e347a81306ef6e19, and cdd2e3d4b39c79cd1d779f3708780a60d8394bd6 are the changes to `_comp_compgen`.
- 47d768368c5f40f36c606f0ae36faf3643da749d is doc changes
- d28e5ea5a7bada1ed13e69a3c0fda0d04c174dd5 is cleanup
> fix: use `_comp_compgen` for the remaining cases

- bash_completion
- completions/_su
- completions/_svn
- completions/cpio
- completions/dpkg
- completions/fio
- completions/firefox
- completions/gdb
- completions/man
- completions/mr
- completions/mussh
- completions/mypy
- completions/perlcritic
- completions/protoc
- completions/querybts
- completions/reportbug
- completions/rpm
- completions/sqlite3
- completions/ssh
- completions/ssh-keygen
- completions/strace
- completions/tar
- completions/tcpdump
- completions/valgrind
- completions/vpnc
- doc/configuration.md
- test/t/unit/Makefile.am
- test/t/unit/test_unit_compgen_commands.py
On some systems, generating the entire list of available commands takes a long time. `no_empty_cmd_completion` is semantically close enough to piggyback on it here.
Closes https://github.com/scop/bash-completion/issues/926
> feat: no empty command completion if `no_empty_cmd_completion` is on

- bash_completion
Previously each config file was read with separate `sed` command to extract `Include` directives. This can get quite slow if there are a lot of included files (on my machine it was ~0.4s for each TAB keypress).
Instead of reading each individual file, we can put all the files at a current recursion level into a single sed invocation and extract all the directives in one go.
> fix(ssh): optimize traversing ssh config includes

- completions/lvm
- test/t/test_lvm.py
- test/test-cmd-list.txt
This fixes an error breaking completion with lvm when called with the `lvm <subcommand>` format. It builds the internal function call to the new function name format and passes in the command line arguments.
Before:
```
lvm lvcreate -bash: _lvcreate: command not found
```
After:
```
lvm lvcreate -
--activate                --ignoreactivationskip    --raidintegrity
--addtag                  --ignoremonitoring        --raidintegrityblocksize
--alloc                   --journal                 --raidintegritymode
--autobackup              --lockopt                 --readahead
```
```
lvcreate -
--activate                --ignoreactivationskip    --raidintegrity
--addtag                  --ignoremonitoring        --raidintegrityblocksize
--alloc                   --journal …
```
> fix(lvm): update call to sub-command

- test/t/test_tree.py
Such as with busybox 1.36.1's `tree` applet.
This is causing test failures currently, such as in https://github.com/scop/bash-completion/actions/runs/5229055368/jobs/9441810374
> test(tree): xfail options test if `--help` contains no options

- completions/eog
Currently eog completion for netpbm format (https://en.wikipedia.org/wiki/Netpbm) only has pgm and ppm, but there is also ppm and is supported by eog.
> Add ppm extension for eog

- completions/eog
I'm not sure what to write here - it is what it says on the tin, I've just added two more file extensions.
> fix(eog): add completion for AVIF and WEBP files

- test/t/test_declare.py
> test(declare): `_comp_compgen` instead of `_parse_help` as test subject

- bash_completion
Closes https://github.com/scop/bash-completion/issues/995
> fix(__load_completion): quoted compspec for variants

- completions/eog
eog supports these via add-on gdk-pixbuf loaders.
> feat(eog): associate with `*.heic` and `*.jxl`

- completions/eog
The support for `.heic` has been added in #1010, but the gdk pixbuf loader, which supports `.heic`, [explicitly supports also `.heif` and `.avif`](https://github.com/strukturag/libheif/blob/4a2f42f01e475258e67371db99108636d32f561c/gdk-pixbuf/pixbufloader-heif.c#L224-L229). The extension `.avif` is already included in the list, but `.heif` is currently missing.
> feat(eog): add missing extension .heif

- completions/python
- test/t/test_python.py
Ref. https://github.com/ohmybash/oh-my-bash/issues/462
When `[-c command | -m module | file]` is already specified before `cword`, the current implementation of the `python` completer tries to complete filenames as arguments to the command/module/script. However, this doesn't work after an option of the form `-?`. The following is a case reported in https://github.com/ohmybash/oh-my-bash/issues/462:
```bash
python some_script.py -p [TAB]
```
The current implementation seems to try to detect the situation by checking the previous and the second previous arguments, but we should explicitly test if `[-c command | -m module | file]` is already specified.
I think this is actually related to the following line that we once discussed in #952 (see replies [1,2]): …
> fix(python): complete filenames for script arguments

- completions/xrandr
Requires/stacks on top of #1025, drafting until that one is merged.
> feat(xrandr): comma separated `--setmonitor` third argument

- bash_completion
- completions/bts
- completions/cvs
- completions/openssl
- completions/python
- completions/ssh
- doc/api-and-naming.md
- test/t/unit/test_unit_compgen.py
To avoid conflicts between local variables and variable names specified by `_comp_compgen -v var`, the local variables basically need to have the name `_foo`.
When a generator needs to call other generators to store results in a local variable, the local variable name cannot have the name `_foo` because it is rejected by the internal generator calls. In such a case, we first declare the variable without the underscore (e.g. `foo`), call the internal generator to store the result to `foo`, move the results to an underscored variable (`_foo`), and remove the local variable `foo` by `_comp_unlocal foo`. The current version of the PR uses this approach.
However, maybe this is too complicated. Another possibility is to add a new option `_comp_compgen -U foo` to internally perform …
> fix(_comp_compgen_*): avoid conflicts with "-v var"

- completions/Makefile.am
- completions/_pipenv
- test/fallback/completions/Makefile.am
- test/fallback/completions/pipenv
https://pipenv.pypa.io/en/latest/shell/#shell-completion
> feat(pipenv): add fallback 3rd party completion loader

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/chown
- completions/cpio
Changes on top of #1028 / Should be considered after merging #1028
> refactor: adjust API/naming of generators

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
These are being used inconsistently here and there, and I don't think there's a need for them in the first place.
> style: remove function end comments

- completions/make
- test/t/test_make.py
Fixes https://github.com/scop/bash-completion/issues/898
> fix(make): handle multiple short options in skipping arguments

- bash_completion
See the commit message for the description. I use bash-completion with `./configure --prefix=... && make install`, but with this setup, the current `master` fails to find `000_bash_completion_compat.bash` and causes issues with external completions.
> fix(compat): find compat dir for prefix-install

- completions/chgrp
Replaces '_comp_compgend filedir' with '_comp_compgen_filedir' in the chgrp completion.
fixes `chgrp git -bash: _comp_compgend: command not found`
> fix(chgrp): typo in chgrp completion

- completions/ssh
This is actually a bug, because the "RequiredRSASize" exists in recent OpenSSH source.
The reason I make this change are as follows:
1. The RequiredRSASize option was added in openssh/openssh-portable@54b333d .
2. RHEL 9.1 changed minimum RSA key size to 2048 by default, broke connections to old SSH servers. Reference: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/9.1_release_notes/new-features#BZ-2066882
3. Fedora Linux sync'd the change from RHEL 9.1. Reference: https://packages.fedoraproject.org/pkgs/openssh/openssh-server/fedora-37.html
4. I was connecting to a legacy device over SSH and tried very hard to remember this option.
I have ran the supplied test for ssh, got the following output:
```
====== 12 passed, 1 xfailed in 35.62s ======
```
> Added RequiredRSASize option for ssh client.

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/7z
- completions/abook
- completions/file-roller
- completions/gcc
- completions/jar
- completions/makepkg
- completions/mussh
- completions/pyvenv
- completions/sha256sum
- completions/vncviewer
- doc/api-and-naming.md
- test/t/test_grep.py
- test/t/unit/test_unit_longopt.py
This is a suggestion for the naming of completion functions (i.e., the functions that are supposed to be specified to `complete -F`) defined in `bash_completion`: In this PR, the completion functions in `bash_completion` have the names of the form `_comp_complete_*`.
> refactor: rename completion functions

- bash_completion
- completions/_nmcli
- completions/convert
- completions/dpkg
- completions/iwconfig
- completions/make
- completions/perl
- completions/portinstall
- helpers/Makefile.am
- helpers/make-extract-targets.awk
- test/runLint
This is the last piece of `#TODO:API`.
This is also the refactoring mentioned in https://github.com/scop/bash-completion/pull/546#issuecomment-871197885. As mentioned there, we might separate the awk script to another file in `helpers/`.
> refactor(make): Use awk to extract target names

- bash_completion
- test/fixtures/_command_offset/completer
- test/t/unit/test_unit_command_offset.py
> fix(_comp_command_offset): Add support for complete -C

- completions/feh
* y4m supported in imlib2 since [1]
* heif Supported in feh through imlib2 since [2]
[1] https://git.enlightenment.org/old/legacy-imlib2/commit/be721b0335845f4d127f6c9041aa98a1d5e7ee22
[2] https://git.enlightenment.org/old/legacy-imlib2/commit/4b4f72c7ffd476df6e450d84f7acb078808cb931
> add y4m and heic/heif/avif extensions to feh

- completions/feh
feh supports several HEIF sub-types through imlib2, which gets the support from libheif. The latter does not support avci/avcs yet.
> feat(feh): deassociate with avci/avcs

- completions/cvs
- completions/dot
- completions/dpkg-source
- completions/invoke-rc.d
- completions/java
- completions/kldload
- completions/mplayer
- completions/mutt
- completions/pkg_delete
- completions/pkgutil
- completions/portupgrade
- completions/povray
- completions/reportbug
- completions/svcadm
- completions/tipc
- completions/vncviewer
- completions/wol
These are a set of trivial fixes that I would like to apply before submitting the _comp_split/_comp_compgen_split/_comp_expand_glob changes.
> fix: fix misc problems before applying `_comp_split` changes

- bash_completion
- bash_completion.d/000_bash_completion_compat.bash
- completions/configure
- completions/cvs
- completions/iwconfig
- completions/tar
- test/t/test_cvsps.py
Move ones in the main `bash_completion` to the compat snippet.
> refactor: mark deprecated config variables clearer

- completions/aspell
- completions/gdb
- completions/java
- completions/mplayer
- completions/openssl
- completions/povray
- completions/wtf
~~Waiting for #1084 and #1085.~~
This is ready.
> fix: refactor unquoted array assignments

- completions/ri
I'm now trying to apply `_comp_split` in `completions/*`, but I decided to submit the changes on `completions/ri` in a separate PR since this file `ri` has many fixes. See the commit message of each commit for the details.
In particular, commit 8c4510d4dfb1ac9897fe066b3eee31f2ec29537f needs double-checking from others. The existing code looks like `COMPREPLY+=("$(... | sort -u)")` where the entire result of the command substitution is quoted, but I suspected that the quoting is unneeded because the result should be separated. However, the quoting seems to have existed from the beginning.
> fix(ri): fix several problems and use `_comp_split`

- .gitlint
For long action ids such as
`google-github-actions/release-please-action`, they end up quite long.
As of gitlint 0.19.1 it seems ignores are not additive, so `body-is-missing` needs to be duplicated here.
> chore(gitlint): ignore title length for bot made commits

- test/t/test_pytest.py
- test/test-cmd-list.txt
It fails if the command doesn't exist, since the options are parsed from the command invocation.
> test: make the pytest option testcase require cmd

- completions/gdb
- test/t/test_gdb.py
The current version fails to generate any command names for the first word after the command name "gdb".  This is a regression introduced in https://github.com/scop/bash-completion/pull/1086 and pointed out in the comment: https://github.com/scop/bash-completion/commit/73c5292b7a39a2f3d1ae01057e0afd3aa24c8a32#r138406647.
> fix(gdb): fix regression that fails to generate command names

- test/docker/debian10/install-packages.sh
https://bugs.debian.org/1040925
> test(debian10): work around openjdk/ca-certificates-java install issue

- completions/xfreerdp
- pyproject.toml
- test/t/test_who.py
The CI test for the `who` command started to fail in the `alpine` container around #1101. However, the changes in #1101 do not seem to be related to the completion of the `who` command. I investigated it and found that the `who` command in the `alpine` container seems to have been replaced by the BusyBox `who` at some point. The detail of the test failure is explained in the commit message. The output of `who --help` in the `alpine` container looks like
```
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
Usage: who [-aH]
Show who is logged on
-a	Show all
-H	Print column headers
```
I also include another commit in this PR to fix the pre-commit error from `ruff-format`, which prevented creating any commits related to tests.
> test: fix test failures

- completions/ip
The ip route usage used to mention monitor as a subcommand, but this was removed in https://github.com/iproute2/iproute2/commit/c0c44bfedda05e52572cc16c9d7777e1077d86cf
Remove it from the completions
> fix(ip): Remove non-existent route completion

- test/t/test_perldoc.py
On some systems the perldoc command exists, but only as a stub that prompts to install the "real" perl-doc pacakge. Skip the test that requires the command if only the stub exists (exits with exit code 1).
> test(perldoc): Test if real perldoc command exists

- bash_completion
- test/t/unit/Makefile.am
- test/t/unit/test_unit_compgen_available_interfaces.py
Fixes #1129
~~I noticed some files are not added in `test/t/unit/Makefile.am`. I added them in the second commit.~~ (**edit**: moved to #1132)
> fix(available_interfaces): fix regression of unwanted trailing colons

- test/fixtures/_comp_load/bin/cmd1
- test/fixtures/_comp_load/bin/cmd2
- test/t/unit/Makefile.am
- test/t/unit/test_unit_load.py
I separate a PR for the test for `_comp_load` from #1131.
----
_Originally posted by @akinomyoga in https://github.com/scop/bash-completion/issues/1131#issuecomment-1987099039_
Tests in `test_unit_load_completion.py` fail. Somehow, the symbolic link and the target are reversed in the tar ball.
```bash
$ LANG=C find test/fixtures/_comp_load -name cmd1 -ls
998988373      0 lrwxrwxrwx   1 murase   murase         19 Dec 25 05:23 test/fixtures/_comp_load/bin/cmd1 -> ../prefix1/bin/cmd1
1015156558      4 -rwxr-xr-x   1 murase   murase         10 Dec 25 05:23 test/fixtures/_comp_load/prefix1/bin/cmd1
1048877481      4 -rw-r--r--   1 murase   murase         56 Dec 25 05:23 test/fixtures/_comp_load/prefix1/share/bash-completion/completions/cmd1
1065355955      4 -rw-r--r--   1 murase   murase …
```
> test: add missing files in `test/t/unit/Makefile.am`

- completions/ip
Network namespaces can have spaces in them, which lead to incorrect completions in that case. Fix it by calling _comp_quote on all namespace names.
There are probably better ways to do this than overwriting `$COMPREPLY`, but I couldn't find one.
> fix(ip): Quote network namespace names

- completions/pkgutil
At least macOS pkgutil is different.
Refs https://github.com/macports/macports-ports/blob/87e757609b6599eda48fedf3afd918d37cf8a85d/sysutils/bash-completion/files/patch-remove-pkgutil.diff
> refactor(pkgutil): load on solaris only

- bash_completion
- completions/Makefile.am
- completions/env
- test/t/test_env.py
- test/t/unit/test_unit_load.py
- test/t/unit/test_unit_realcommand.py
Refs https://github.com/scop/bash-completion/issues/1111
> feat(env): complete commands and variable assignments

- bash_completion
- completions/_nox
- completions/add_members
- completions/apt-get
- completions/arch
- completions/change_pw
- completions/check_db
- completions/clone_member
- completions/config_list
- completions/find_member
- completions/inject
- completions/list_admins
- completions/list_members
- completions/list_owners
- completions/mysql
- completions/newlist
- completions/perl
- completions/pydoc
- completions/remove_members
- completions/rmlist
- completions/rpm
- completions/ssh
- completions/ssh-copy-id
- completions/ssh-keygen
- completions/sync_members
- completions/withlist
- test/t/conftest.py
These are fixes for the builtins receiving arbitrary strings as strings (but not as options). This generalizes the `type -P` fix in #1118.
> fix: use `--` to pass an arbitrary string to builtins

- completions/fio
- test/t/test_fio.py
Rows in `--enghelp` output that contain engine names start with a tab as of fio 3.35.
Remove spurious closing parenthesis introduced in commit a1dd4d0c8912a9e04952e88d96447585fe25572e.
> fix(fio): engines completion

- completions/ip
These values don't take any arguments, so we can keep completing right after them.
> fix(ip): Don't stop at proxy and nomaster in neigh

- completions/ssh
Fixes #1157
The explanation is in the commit message. I haven't added a test since it is related to the remote configuration. It reminds me of the mechanism `LIVE_HOST` discussed in #910, which I'm not sure of.
There is an additional fix to localize the change to `cur`.
> fix(scp remote_files): do not filter generated paths with "$cur"

- completions/cryptsetup
An encrypted device's header should be stored in a file. This change enables filename completion for cryptsetup's --header option.
> fix(cryptsetup): add file completions to header option

- bash_completion
- test/t/unit/test_unit_compgen_available_interfaces.py
Leave other punctuation alone, at least for now.
Closes https://github.com/scop/bash-completion/issues/1133
See also discussion starting from https://github.com/scop/bash-completion/pull/1131#discussion_r1518797675
> fix(available_interfaces): strip only trailing colon from entries

- completions/java
- test/fixtures/java/JEP330.java
- test/t/test_java.py
Modify java command completion scripts to also complete filenames with the .java extension. This adds support for
- JEP 330: Launch Single-File Source-Code Programs
- JEP 458: Launch Multi-File Source-Code Programs
----
edited by @akinomyoga
Fixes #1196
> feat(java): enable .java filename completion for java command

- completions/Makefile.am
- configure.ac
https://github.com/scop/bash-completion/pull/1210 resurrected
> build: don't install various tools on non-applicable platforms

- completions/Makefile.am
- completions/_sops
- test/fallback/completions/Makefile.am
- test/fallback/completions/sops
https://github.com/getsops/sops
> feat(sops): add 3rd party fallback completion loader

- bash_completion
Fixes #1207. Now `_comp_expand_glob` adjusts `LC_COLLATE` (2d7b9b136) and the files in compatibility directories are generated by `_comp_expand_glob` (0beaa288b).
In addition to the fix, I modified `_comp_expand_glob` to take account of the new `GLOBSORT` added in Bash 5.3 (1322589f1).
This is just refactoring, but I also moved the codes to list the files in a function since the number of temporary global variables is increasing (f6c99d7). Only the list of the files to source is written to the global variable `_comp__init_startup_configs`, and the files are sourced outside the function.
> fix(_comp_expand_glob): set LC_COLLATE for the sorting order

- test/t/test_ifdown.py
- test/t/test_ifup.py
Without network we likely don't have any interfaces configured either
Fixes: https://github.com/scop/bash-completion/issues/479
> test(ifdown,iftest): Skip if we don't have network

- .gitignore
`autoreconf -i` on at least Ubuntu 24.04 adds them.
> chore(git): ignore config.guess and config.sub

- completions/curl
- test/t/test_curl.py
Every option that reads files using `@` allow also `-` for stdin
> Complete stdin "-" in file locations, add more options that allow it

- completions/tar
- test/t/test_tar.py
Fixes: https://github.com/scop/bash-completion/issues/98
> tar: Complete adding files to archive with long options

- completions/rsync
- completions/ssh
- test/t/test_rsync.py
- test/t/test_scp.py
Fixes #848.
If a remote machine contains a file named `a b`, completing rsync command results in `rsync remote:a\\\ b`, which results in rsync failing to find the file.
This commit removes the extra slashes, and now completion results in `rsync remote:a\ b`.
scp somehow accepts both variants, so this change won't break it.
> fix(rsync,ssh): do not overescape spaces in remote filenames

- .pre-commit-config.yaml
- test/fixtures/mount/bin/showmount
- test/fixtures/scp/bin/ssh
- test/t/test_scp.py
Since there doesn't seem to be any unit tests for xfuncs, I'm not sure if the naming here makes sense, or if I should make some more directories, for example a `unit/xfunc` or `fixtures/xfunc`?
I did this since there seems to be a lot of issues with this function, as seen in https://github.com/scop/bash-completion/pull/910 and https://github.com/scop/bash-completion/pull/765#issuecomment-1173097965
This should be a first good step to make fixing the issues easier IMO.
> test(scp): Add unit tests for getting remote files

- completions/dpkg
Completion for '--raw-extract' is already supported, however the equivalent short option '-R' was missing. Now fixed.
Cf. dpkg-deb help message:
```
dpkg-deb --help
[...]
-R|--raw-extract <deb> <directory>
[...]
```
> fix(dpkg): Add missing short option -R

- completions/.gitignore
- completions/Makefile.am
https://ngrok.com/docs/agent/cli/#ngrok-completion
> feat(ngrok): add 3rd party fallback completion loader

- completions/openssl
- test/t/test_openssl.py
Instead we get the command list by parsing openssl help, which also adds some subcommands that were missing, and removes some non-existant ones (at least on versions I have).
The parsing only happens when it's necessary, when the subcommand wasn't chosen.
> feat(openssl): Stop having subcommands hardcoded

- bash_completion
- completions/Makefile.am
- completions/_mtr
- test/t/Makefile.am
- test/t/test_mtr.py
https://github.com/traviscross/mtr/tree/v0.95/bash-completion
While at it, add basic test.
> refactor(mtr): deprecate our completion, upstream >= 0.88 has one

- completions/.gitignore
- completions/Makefile.am
- completions/_insmod
- completions/_modinfo
- completions/_modprobe
- completions/_rmmod
- test/fallback/completions/Makefile.am
- test/fallback/completions/insmod
- test/fallback/completions/modinfo
- test/fallback/completions/modprobe
- test/fallback/completions/rmmmod
I'm aiming to have these in the upstream project and having the ones in bash-completion means that distributions will get clashing files. 
Rename these with the fallback prefix and (try) to fix all the build magic ;-)
> Deprecate {ins,rm}mod and mod{info,probe}

- bash_completion
- test/t/unit/test_unit_abspath.py
Depending on the setup, we source the completion files with relative paths. This causes a problem when a completion script uses `BASH_SOURCE` to specify the helper script after the current working directory is changed. For example, with the following steps, the problem happens:
```bash
$ bash --norc
$ source bash_completion
$ make [TAB]
$ cd testdir
$ make [TAB]awk: fatal: cannot open source file `./completions/../helpers/make-extract-targets.awk' for reading: No such file or directory
```
This is because `_comp_cmd_make__extract_targets` (called by `_comp_cmd_make`) uses `BASH_SOURCE` to identify the location of the helper script, but `BASH_SOURCE` contains a relative path from the directory where the completion file is first sourced.
```bash
$ complete -p make
complete -F _comp_cmd_make …
```
> fix: source files using absolute paths for absolute BASH_SOURCE

- .github/requirements.txt
- .pre-commit-config.yaml
pre-commit 4.0.1 warns:
> top-level `default_stages` uses deprecated stage names (commit)
> which will be removed in a future version.
Use new names, means pre-commit >= 3.2.0 is required now.
> chore(pre-commit): avoid stage name deprecation warning

- completions/wine
Closes https://github.com/scop/bash-completion/issues/1257
> feat(wine): complete with `*.bat` and `*.cmd`

- bash_completion
As mentioned in https://github.com/scop/bash-completion/issues/704#issuecomment-1515960552, `@algorythmic` has added `compgen -V array_name` in the new version of Bash 5.3, which can be used to handle the completions including newline characters properly.
- 7c125358e In the first commit, I split the function `_comp_compgen` into two (for `_comp_compgen <generator>` and for `_comp_compgen -- <options for builtin compgen>`).
- 0ec92f2e8 In the second commit, I prepare an implementation for Bash 5.3 using `compgen -V`.
**edit**: Although the CI tests with Bash 5.3 are not set up, I locally ran tests with Bash 5.3 (more specifically, with the `devel` ranch of Bash) and confirmed that this change does not break the tests.
> fix: use Bash 5.3 `compgen -V` to generate completions including newlines

- bash_completion
- test/fixtures/shared/bin/ip
- test/t/unit/test_unit_compgen_xinetd_services.py
resolves #1089
Same with this https://github.com/scop/bash-completion/blob/2b7fc195aeb404b41bc3e5fa8c1e98f10f1ee26a/completions/wol#L18
> fix: prefer using iproute2 instead of ifconfig

- .github/workflows/ci.yaml
This was added as a workaround for [0], but from reading [1] it seems this is fixed when running with libseccomp >= 2.4.4, which all supported ubuntu versions since March 2021 have [2]. CI runs with ubuntu-latest which is currently ubuntu-24.04, with 2.5.5. 
[0] https://bugzilla.redhat.com/show_bug.cgi?id=1900021
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1900021#c26
[2] See 20.04 changelog: https://changelogs.ubuntu.com/changelogs/pool/main/libs/libseccomp/libseccomp_2.5.1-1ubuntu1~20.04.2/changelog
This reverts d19d24a3b4d7efeb24d7e0e6c94c248149510c37
> ci: Stop running fedoradev with seccomp=unconfined

- test/t/test_modinfo.py
- test/t/test_modprobe.py
These tests failed on WSL, which doesn't complete anything that starts with intel. I don't have a machine to test, but I expect this will also fail on arm or amd machines.
Instead, we expect it to complete "dummy", a network driver.
> test(mod{probe,info}): Don't expect intel completion

- test/t/unit/test_unit_realcommand.py
This function doesn't actually exist. Also added an error message, this really should never happen.
> test(realcommand): Don't use pytest.skipif

- completions/Makefile.am
- configure.ac
This should fix https://github.com/scop/bash-completion/issues/1282, although still doesn't deal with the issue of including tests for them or not.
I will love if people who actually know Makefile/autotools will look at this :)
I'm not really sure about the variables naming, open for suggestions.
> build: Include OS specific completions in tarball

- test/fallback/completions/Makefile.am
- test/fallback/completions/mtr
Missed from 231a39d428c5a76b0fd02faf0ee0bbb3cf9f17c1.
> test(mtr): add fallback completion symlink

- completions/Makefile.am
- completions/mfiutil
- test/t/Makefile.am
- test/t/test_mfiutil.py
[**mfiutil(8)**](https://man.freebsd.org/cgi/man.cgi?query=mfiutil&manpath=FreeBSD+14.1-RELEASE) is available as a part of FreeBSD base system; [a portable version](https://sourceforge.net/projects/mfiutil/) is also available for a few other operating systems.
> Add completion for mfiutil(8)

- .github/workflows/ci.yaml
google-github-actions/release-please-action is deprecated and archived.
> ci(release-please): switch to googleapis/release-please-action

- completions/brctl
I had a "pending" review in #866 that I forgot to submit. This is a trivial fix, so let me just submit it here for the CI checking. If the test passes, I will soon merge. This quotes the command name `${1:-brctl}` as `"${1:-brctl}"`. This also changes the line folding because the line does not fit within 79 columns.
> fix(brctl): fix quoting of the command name

- completions/.gitignore
- completions/Makefile.am
Missed from https://github.com/scop/bash-completion/pull/1241
> chore(mfiutil): clean up and ignore mrsasutil symlink

- completions/Makefile.am
- completions/nload
- test/t/Makefile.am
- test/t/test_nload.py
- test/test-cmd-list.txt
https://www.roland-riegel.de/nload/
More or less dormant project, does not look like there's much chance to get changes applied in timely manner, so submitting here.
> feat(nload): new completion

- .pre-commit-config.yaml
pre-commit CI runs started failing on the perlcritic step, so update to the last version of the perlcritic pre-commit hook, corresponding to perlcritic v1.156
It will be preferable to make renovate update this, but I'm not sure why it doesn't do it. Any thoughts @scop @akinomyoga ?
> chore(perlcritic): Update perlcritic

- test/t/unit/test_unit_count_args.py
- test/t/unit/test_unit_dequote.py
- test/t/unit/test_unit_get_first_arg.py
- test/t/unit/test_unit_quote.py
This might help with #430...
In my case, test/t/unit/test_unit_command_offset.py's test_cmd_quoted is the only one still failing
Original commit message follows:
-- 8< --
When running the test suite with xdist and 'pytest -n <jobs>', several tests fail. This happens because, in these tests, the definition of the testing function, usually in a method called 'functions' might happen after the execution of the tests themselves, i.e. in the methods whose names start with 'test_'.
This patch adds 'autouse=True' to these test-function-defining methods, so that they are executed before the tests.
> Add missing dependency on fixtures to help parallel testing

- bash_completion
This is a patch in Debian's downstream which I think belongs here.
It was originally reported to Ubuntu at https://bugs.launchpad.net/ubuntu/+bug/311525
> feat: associate .ogx and .oga with relevant programs

- completions/curl
- completions/wget
- test/t/test_curl.py
- test/t/test_wget.py
Closes https://github.com/scop/bash-completion/issues/1315
> curl, wget: Complete IP addresses, including ipv6 for --interface and --bind-address

- completions/ip
- test/t/test_ip.py
The previous state led to `ip neigh<TAB>` leading to this:
```
$ ip neighbo
neighbor   neighbour
```
choosing one to complete removes the need to choose between options that do the same thing, aligning with the CONTRIBUTING.md guidelines.
I chose `neighbor` because it's shorter, but it can be changed if someone wants to.
> fix(ip): Don't offer neighbour, only neighbor

- completions/aptitude
This fix has been provided to Debian (downstream) by Heinrich Schuchardt <heinrich.schuchardt@canonical.com>. It is currently a downstream patch, but it should be here.
> feat(aptitude): add showsrc and source options

- completions/openssl
- test/t/test_openssl.py
This should fix https://github.com/scop/bash-completion/issues/1324
This replaces https://github.com/scop/bash-completion/pull/1325, which doesn't work on some openssl versions
> openssl: Fix completions for MacOS, don't complete algorithms as subcommands

- bash_completion
XAPK/APKM/APKS are all ZIP containers for shipping Android apps.
* APKS https://developer.android.com/tools/bundletool#generate_apks
* XAPK https://openxapkfile.net/structure.html
* APKM https://fileinfo.com/extension/apkm
> support Android  app bundles as 'unzip' file type (XAPK/APKM/APKS)

- completions/_umount.linux
- completions/feh
- completions/sbopkg
Fixes #1260
This is an alternative fix to #1290. The fix suggested in #1290 was just to remove the error message, which I believe is not the right fix. This PR fixes it by checking the arguments at the caller side.
This includes an additional fix e9e665efd7623dd9ec6d72c25c5797c497d58f65 for `feh`. In the current `main` branch, an error message is printed on the TAB completion with the following command line:
```console
$ set -u
$ feh --font x[TAB] --fontpath
bash: words[i + 1]: unbound variable
```
> fix(_umount,feh,sbopkg): check diretory name for `_comp_compgen -C`

- completions/Makefile.am
- completions/free
- test/t/Makefile.am
- test/t/test_free.py
- test/test-cmd-list.txt
Regarding upstreaming, https://github.com/scop/bash-completion/pull/1247#issuecomment-2380654685 applies here too.
> feat(free): new completion

- completions/rpm
While the `--rebuild` option isn't deprecated, [the man page now notes that the `-r?` options supersede it](https://www.man7.org/linux/man-pages/man8/rpmbuild.8.html).
Treats `-r?` as equivalent to `--rebuild` for determining which extensions to complete
> feat(rpm): rpmbuild short rebuild options

- completions/tar
In my setup, the `tar` completion has been somehow significantly slower than the other completions. It turned out that the help parsing, which is performed for every call of the tar completion, has been the bottleneck. This PR introduces a cache for the parse result, which significantly improves the performance of the tar completion.
The main change is 5a851086bf0eddb8aa09174913d76bf114b00659. There are other refactoring commits, but those changes are independent.
> perf(tar): cache the parse result of GNU tar help

- completions/cd
- test/t/test_cd.py
When `shopt -s cdable_vars` is set, all the variable names are generated as completions. For example, in my environment,
```console
$ shopt -s cdable_vars
$ cd [TAB][TAB]
Display all 177 possibilities? (y or n)
_                               bleopt_connect_tty              CPLUS_INCLUDE_PATH              GUESTFISH_PS1                   MAIL                            prefix                          test/
_append                         BLE_SESSION_ID                  _cur                            GUESTFISH_RESTORE               MAILCHECK                       prev                            test2/
archive/                        _ble_util_fdlist_cloexec        cur                             _has_ifs                        MANPATH                         PS1 …
```
> fix(cd): generate only cdable_vars containing valid directory paths

- test/docker/fedoradev/Dockerfile
- test/docker/fedoradev/install-packages.sh
vpnc causes this error:
```
Running transaction
Transaction failed: Rpm transaction failed.
- file /usr/bin/vpnc conflicts between attempted installs of vpnc-consoleuser-0.5.3-48.svn550.fc41.x86_64 and vpnc-0.5.3-48.svn550.fc41.x86_64
- file /usr/bin/vpnc-disconnect conflicts between attempted installs of vpnc-consoleuser-0.5.3-48.svn550.fc41.x86_64 and vpnc-0.5.3-48.svn550.fc41.x86_64
```
> Fedoradev image: don't install vpnc, update for dnf5

- test/docker/centos7/Dockerfile
Closes https://github.com/scop/bash-completion/issues/1368
CI fail is unrelated.
> test(docker): fix centos7 image build

- .github/workflows/ci.yaml
- test/docker/alpine/Dockerfile
- test/docker/centos7/Dockerfile
- test/docker/debian10/Dockerfile
- test/docker/entrypoint.sh
- test/docker/fedoradev/Dockerfile
- test/docker/ubuntu14/Dockerfile
- test/t/test_scp.py
This should allow us to make better tests for remote files in scp and rsync completions.
CI in this PR fails because the images are only pushed after merging
> Run sshd in CI

- completions/xfreerdp
This caused failures on recent fedoradev rawhide tests, since it seems to not be built with deprecated options like `--list-kbd` anymore.
This introduces an internal utility function to list kbd layouts, which is used in two places.
I'm not sure about how the usage of the function, I couldn't find other utility functions that don't just complete something right away, but I didn't look very thoroughly. Maybe returning the data through a variable like REPLY makes more sense?
> fix(xfreerdp): try /list:kbd also with dash syntax

- completions/convert
In image magick 7 running `convert` prints a warning. Try running magick first.
```
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
```
Another alternative is to just swallow the warning from `convert`, but this seems a bit more future proof.
> fix(convert): Try calling magick, for IM7

- completions/Makefile.am
- completions/tmux
- test/t/Makefile.am
- test/t/test_tmux.py
From https://github.com/tmux/tmux/pull/259 it doesn't look like the tmux maintainers were interested in having a bash completion script in the upstream repo. However, I added license headers to put these new files under either bash-completion's license or tmux's, in case they want it there in the future.
I'm aware of a handful of existing tmux bash completion scripts, below. As far as I can tell, they all hard-code a decent amount of tmux's available options, commands, etc. Some are also abandoned and out of date with more recent versions of tmux. Rather than base this code off of those, I decided to implement completion using tmux's own introspection commands as much as possible. Hopefully that will reduce the ongoing maintenance work and make it stay up to date with most tmux changes …
> feat(tmux): new completion

- test/t/test_fprintd_enroll.py
Containers usually don't have fingerprint readers
> test(fprintd): xfail --finger in container

- completions/xfreerdp
This is the only option that seems to work in xfreerdp 1.0.2, which is what comes with ubuntu 14.04.
Follow up to https://github.com/scop/bash-completion/pull/1373
> fix(xfreerdp): try `--list-kbd` as last resort

- test/t/unit/test_unit_compgen_available_interfaces.py
We have a fallback to `ifconfig` if `ip` doesn't exist, but it wasn't tested anywhere that does have `ip` (pretty sure that's all of our current distro tests).
Introduce a parameterized fixture that "hides" `ip` or `ifconfig` and, use it in tests.
Also introduce another test that actually makes sure that we find the correct interfaces.
Follow up to https://github.com/scop/bash-completion/pull/1090
> test(interfaces): Test for missing ip or ifconfig

- completions/ssh
- test/t/test_scp.py
This was a part of #1371 but was separated.
Details are described in the commit message.
> fix(scp): fix a bug that `-F<prefix>[TAB]` did not complete at all

- test/fixtures/shared/bin/ifconfig
- test/fixtures/shared/bin/ip
- test/t/unit/test_unit_compgen_available_interfaces.py
Follow up to https://github.com/scop/bash-completion/pull/1393
Depends on https://github.com/scop/bash-completion/pull/1394
> test(interfaces): Test completion of veth peers

- completions/ssh
- test/t/test_scp.py
This was a part of #1371 but was separated. Waiting for #1397.
Details are described in the commit message.
> [Waiting for #1397] fix(rsync,scp): remove file-type marks from "ls -F" properly

- README.md
This updates the descriptions for `command_not_found_handle`. The change in README explains itself.
**edit**: Background
- https://github.com/junegunn/fzf/pull/4468
- https://github.com/pkasemir/find-the-command/issues/8
> docs(README): update requirements on `command_not_found_handle`

- bash_completion
- completions/tar
.hap is the extension of HarmonyOS app package, which is a zip.
> bsdtar and unzip should support .apk, .ipa and .hap

- bash_completion
See the commit message.
> https://github.com/scop/bash-completion/pull/1404#issuecomment-3147310228
>
> I don't see a problem adding more of them. crx would fit in well if it's a zip, we have xpi already which is corresponding thing for Firefox.
>
> https://github.com/scop/bash-completion/pull/1404#issuecomment-3147329632
>
> But re these, would be great to provide URLs to some sample files with which reviewers could verify that they work with these tools. 
I've included the reference URL in the commit message as usual, but it might be harder to track the changes later because many extensions are included in a single line where `git blame` isn't useful to identify a commit that added a specific filename extension. Maybe we should include the reference information directly in the code …
> feat(unzip,zipinfo): generate *.crx for Google Chrome Extension's ZIP archives

- bash_completion
- completions/ssh
- test/t/test_cancel.py
- test/t/test_ls.py
- test/t/test_man.py
I separated small changes out of #1357. There are still eight commits, but I think they are mostly trivial fixes. If this is still too large as a PR, I'll further split the PR.
For these small changes, there are no ongoing discussions in #1357.
I'm thinking of separating the other *non-trivial* changes into PRs with smaller numbers of commits. I'll submit them after merging this PR.
> fix(scp,rsync): fix misc bugs and refactor

- README.md
If the `bash-completion.pc` file is not available during build,
the build system would fall back to using the legacy `compatdir`.
Let’s update the fallback to make it consistent with the optimistic branch.
> docs(README): Suggest using `completionsdir` as a fallback

- completions/ssh
This is another PR separated from #1357. This commit is just trivial refactoring, but the next commit is nontrivial. I decided to submit this single commit before submitting the rest.
> refactor(scp): factorize common codes

- completions/java
- completions/ssh
- test/t/test_rsync.py
- test/t/test_scp.py
Separated from #1357.
Fixes #1232
> fix(java,rsync,scp): handle quoted space in filepaths properly 

- .github/renovate.json
Our previous "config:base" was actually these days called "config:recommended":
https://docs.renovatebot.com/presets-config/#configrecommended
"config:best-practices":
https://docs.renovatebot.com/presets-config/#configbest-practices
> chore(renovate): use best-practices preset

- bash_completion
- test/t/unit/test_unit_parse_help.py
A followup to #1425 with two commits addressing independent topics.
Should now detect these properly:
```
-n MODE[,STATUS[,STATUS2]], --nocheck=MODE[,STATUS[,STATUS2]] (ATA, SCSI)
-s NAME[,VALUE], --set=NAME[,VALUE]
-B [+]FILE, --drivedb=[+]FILE                                       (ATA)
```
> feat(_comp_compgen_help): enhance for smartctl

- test/t/test_make.py
> Move deletion of extra makefile to fixture, don't do it on macos

- test/t/unit/test_unit_expand_glob.py
Some of the files have unicode characters that can be represented in multiple ways, so we normalize them. Specifically: 'e\u0301' ('e' + 'Combining Acute Accent') doesn't equal '\xe9' ('LATIN SMALL LETTER E WITH ACUTE') unless you normalize them.
Cherry-picked from #1339
> test(glob): Normalize some strings to compare

- .github/renovate.json
Setting it conflicted, see
https://docs.renovatebot.com/configuration-options/#rebasewhen
Hopefully this will stop it from rebasing everytime a PR is merged.
Ref: https://github.com/scop/bash-completion/pull/1416
> ci(renovate): Set rebaseWhen explicitly

- CONTRIBUTING.md
- README.md
- change markdown code-block lang-tags from `shell` to `bash` (only where appropriate)
- check if completions are already sourced in example `.bashrc` (in `README`)
fixes #1443
> doc improvements
